var path=require("path"),Promise=require("bluebird"),inq=require("inquirer"),log=require("npmlog"),Table=require("easy-table"),fs=Promise.promisifyAll(require("fs-extra")),readJsonSync=require("./util/json").readJsonSync,readJsonAsync=require("./util/json").readJsonAsync,copyToDirAsync=require("./util/copy").copyToDirAsync,merge=require("./util/merge"),Git=require("./util/git"),git=new Git;
function Generator(h){function k(b){if(b){var e=path.join(__dirname,"..");b=fs.readFileSync(b);b=b.toString().replace(/\$cli-root/gi,e).replace(/\\/g,"/");d=JSON.parse(b)}else d=null}var d;k(h);this.setTmplates=k;this.getTemplates=function(){return d}}
Generator.prototype.showTemplates=function(h,k){var d=this.getTemplates(),b=new Table,e={webapp:"Web App",nativeapp:"Native App",webappinfo:"Web App Info",nativeappinfo:"Native App Info",jsservice:"JS Service",nativeservice:"Native Service",jsserviceinfo:"JS Service Info",nativeserviceinfo:"Native Service Info",icon:"Icon",library:"Library"},a;for(a in d)if(!0!==d[a].hide&&d[a].type){var n=d[a]["default"]?"(default) ":"",q=d[a].branch||"-",p=e[d[a].type]||d[a].type;k&&-1===["true","false",!0,!1].indexOf(k)&&
d[a].type&&null===d[a].type.match(new RegExp(k+"$","gi"))||(b.cell("ID",a),b.cell("Project Type",p),b.cell("Version",q),b.cell("Description",n+d[a].description),b.newRow())}console.log(b.print())};
Generator.prototype.existOutDir=function(h){log.verbose("Generator.existOutDir()",h);try{if(0<fs.readdirSync(h).length)return!0}catch(k){if(k&&"ENOTDIR"===k.code)throw Error(dest+" is not a directory. Please check the directory path.");if(k&&"ENOENT"===k.code)return log.verbose("Generator.generate()","The directory does not exist."),!1;throw k;}};
Generator.prototype.generate=function(h){function k(a,l){var c=[].concat(a.path);return Promise.all(c.map(function(a){return fs.lstatAsync(a).then(function(c){if(!c.isFile())throw c="Invalid metadata template path:"+a,log.warn("Geneator.generate()._writeURLdata()#warn","Invalid metadata template path:"+a),Error(c);c=fs.readFileSync(a,"utf8");c=c.replace(/(?:['"])([:/.A-z?<_&s=>0-9;-]+')/,"'"+l+"'");path.basename(a);var f=path.join(m,path.basename(a));fs.writeFileAsync(f,c,{encoding:"utf8"})})})).then(function(a){log.verbose("Geneator.generate()._writeMetadata() done.")})["catch"](function(a){log.verbose("Geneator.generate()._writeMetadata()#err:",
a);throw a;})}function d(a,l,f){log.verbose("Generator.generate()._writeMetadata()");var c=[].concat(a.path);l=l||{};f=f||{};return Promise.all(c.map(function(c){return fs.lstatAsync(c).then(function(b){if(!b.isFile())throw b="Invalid metadata template path:"+c,log.warn("Geneator.generate()._writeMetadata()#warn","Invalid metadata template path:"+c),Error(b);b=readJsonSync(c);var d=path.basename(c);"appinfo.json"===d?b=merge(b,l):"services.json"===d?b=merge(b,f):"package.json"!==d||"jsserviceinfo"!==
a.type&&"nativeserviceinfo"!==a.type||(b.name=f.id||b.name);return b}).then(function(a){var f=path.join(m,path.basename(c));return fs.mkdirsAsync(m).then(function(){return fs.writeFileAsync(f,JSON.stringify(a,null,2),{encoding:"utf8"})})})})).then(function(a){log.verbose("Geneator.generate()._writeMetadata() done.")})["catch"](function(a){log.verbose("Geneator.generate()._writeMetadata()#err:",a);throw a;})}function b(a,f,b,d){var c=[],l;for(l in a.sources)c.push({url:a.sources[l],target:b||a.targets[l],
locate:a.locates?path.join(f,a.locates[l]):path.join(f,"lib")});return Promise.all(c.map(function(a){try{fs.accessSync(a.locate,fs.F_OK);if(!d)throw Error(a.locate+' exits. Please set "overwrite".');log.verbose("_downloadLibs()#Removing an existing directory at ",a.locate);return fs.removeAsync(a.locate).then(function(){return git.shallowClone(a.url,a.locate,a.target)})}catch(r){if(r&&"ENOENT"===r.code)return log.verbose("_downloadLibs()",a.locate+" does not exists. start git shallow clone."),git.shallowClone(a.url,
a.locate,a.target)}})).then(function(c){log.verbose("_downloadLibs() done.");return a})["catch"](function(a){log.verbose("_downloadLibs()#err:",a);throw a;})}var e=h.tmplName,a=h.appinfo,n=h.svcName,q=h.out,p,f=this.getTemplates(),m=path.resolve(q),g=f[e];if(!g||"requireCommands"===e)return Promise.reject(Error("Invalid template name"));g.metadata&&g.metadata.data&&"object"===typeof g.metadata.data&&(a=merge(a,g.metadata.data));n&&(p={},p.id=n,p.services=[{name:n}]);return Promise.resolve().then(function(){if(f.requireCommands&&
-1!==f.requireCommands.indexOf("git"))return git.verifyGit({openUrl:!0})}).then(function(){log.verbose("Generator.generate()","template name:"+e);console.log("Generating "+e+" in "+m);if(g.type.match(/info$/))return d(g,a,p);if(g.type.match(/^Hosted/)){var c=[].concat(g.path);return Promise.all(c.map(function(a){return copyToDirAsync(a,m)})).then(function(){var b,e;g.metadata&&g.metadata.id&&(b=f[g.metadata.id]);if(b){if(a.url){e=a.url;delete a.url;var h={path:path.join(c[0],"index.html")};k(h,e)}return d(b,
a,p)}})}c=[].concat(g.path);return Promise.all(c.map(function(a){log.verbose("Generator.generate()","template src:"+a);return copyToDirAsync(a,m)})).then(function(){var c;g.metadata&&g.metadata.id&&(c=f[g.metadata.id]);if(c)return d(c,a,p)})}).then(function(){return Promise.all((f[e].deps||[]).map(function(a){if(f[a]){if(f[a].path)return copyToDirAsync(f[a].path,m);log.warn("Generator.generate()","Invalid template path "+a)}else log.warn("Generator.generate()","Invalid template id "+a)}))}).then(function(){if(!g.type.match(/info$/)&&
!g.type.match(/icon$/)){log.verbose("Generator.generate()","target branch is "+f[e].branch);var a;a=path.join(m,".enyoconfig");try{return fs.accessSync(a,fs.F_OK),readJsonAsync(a).then(function(a){return b(a,m,f[e].branch,h.overwrite)}).then(function(b){if(b&&b.targets){for(var c in b.targets)b.targets[c]!==f[e].branch&&(b.targets[c]=f[e].branch);return fs.writeFileAsync(a,JSON.stringify(b,null,2))}})}catch(l){if(l&&"ENOENT"===l.code)log.verbose("Generator.generate()",a+" does not exist.");else throw l;
}}}).then(function(){log.verbose("Generator.generate() done.");return{msg:"Success"}})["catch"](function(a){log.verbose("Generator.generate()#err:",a);throw a;})};
Generator.prototype.init=function(h){function k(a,b){var d=[];log.verbose("Generator.init()._checkoutLibs()");for(var e in a.sources)d.push({url:a.sources[e],target:a.targets[e],locate:a.locates?path.join(b,a.locates[e]):path.join(b,"lib")});return Promise.all(d.map(function(a){try{return fs.accessSync(a.locate),git.unshallowRepo(a.locate).then(function(){return git.checkoutRepo(a.locate,a.target)})}catch(m){if(m&&"ENOENT"===m.code)return log.verbose("Generator.init()._checkoutLibs()",a.locate+" does not exist."),
log.verbose("Generator.init()._checkoutLibs()","git shallow clone "+a.url+" # branch: "+a.target),git.shallowClone(a.url,a.locate,a.target);throw m;}})).then(function(a){log.verbose("Generator.init()._checkoutLibs() done.")})["catch"](function(a){log.verbose("Generator.init()._checkoutLibs()#err:",a);throw a;})}var d,b=path.resolve(h.out),e=path.join(b,".enyoconfig");log.verbose("Generator.init()","options:"+h);try{if(d=fs.statSync(b),!d.isDirectory())throw Error(b+" is not a directory.");}catch(a){if(a&&
"ENOENT"===a.code)throw Error(b+" does not exist.");}return Promise.resolve().then(function(){return git.verifyGit({openUrl:!0})}).then(function(){try{var a;fs.accessSync(e,fs.F_OK);a=readJsonSync(e);console.log("Initializing as described in "+e);return k(a,b)}catch(n){throw n&&"ENOENT"===n.code&&(n=Error(e+" does not exist.")),n;}}).then(function(){log.verbose("Generator.init() done");return{msg:"Success"}})["catch"](function(a){log.verbose("Generator.init() err:",a);throw a;})};module.exports=Generator;
