var fs=require("graceful-fs"),request=require("request"),path=require("path"),log=require("npmlog"),async=require("async"),mkdirp=require("mkdirp"),shelljs=require("shelljs"),extract=require("extract-zip"),appdata=require("./cli-appdata");
(function(){function n(){this.templates=[];this.libraries=[]}var x=path.join(__dirname,"json/templates_all.json"),h=new appdata,y=h.getConfig(!0).templatesServer||"";n.prototype={setTemplatesList:function(a){function p(a,q){var f=h.getConfig(!0);for(index in a){var e=a[index];if(e.hasOwnProperty("profile")&&-1!==e.profile.indexOf(f.profile)&&e.openLevel<=f.openLevel){var k=c.templates.filter(function(a){return a.id===e.id});if(0==k.length)c.templates.push(e);else for(prop in e)k[0][prop]=e[prop]}}setImmediate(q)}
var c=this;async.waterfall([function(a){log.verbose("generate#setTemplatesFromLocal()");var c=fs.readFileSync(x,"utf8");try{var f=JSON.parse(c).templates;setImmediate(a,null,f)}catch(e){return a(Error("JSON Parse Error:",e))}}.bind(c),p.bind(c),function(a){log.verbose("generate#setTemplatesFromServer()");request(y,function(f,h,e){if(f||200!=h.statusCode)setImmediate(a,null,{});else{try{var k=JSON.parse(e).templates;c.templates=c.templates.concat(k)}catch(t){setImmediate(a,null,{})}setImmediate(a,
null,k)}})}.bind(c),p.bind(c)],a)},getTemplatesList:function(a){return a&&"function"===typeof a?a(null,this.templates):this.templates},getTemplatesBy:function(a,h,c){var f=this.templates.filter(function(c){return c[a].toLowerCase()===h.toLowerCase()});return c&&"function"===typeof c?c(null,f):f},generate:function(a,p,c){function f(b){return l.templates.filter(function(a){return a.id===b})}function q(b,m){log.verbose("generate#_processTemplate()","processing Template:",b);a.version=a.version||"0.0.0";
var d=f(b)[0];if(!d)return m();if(d.files)try{var g=JSON.stringify(d.files),g=g.replace(/@PLUGINDIR@/g,h.getAppDir()).replace(/\\/g,"/"),g=g.replace(/@VERSION@/g,a.version);d.files=JSON.parse(g)}catch(z){return m(z,Error("JSON Parse Error : template data is invalid!!"))}d.files=d.files||[];d.deps=d.deps||[];async.series([async.forEachSeries.bind(this,d.deps,q),async.forEachSeries.bind(this,d.files,n)],m)}function n(b,a){log.verbose("generate#_processSourceItem()","processing Source Item:",b);b.url?
(b.at=b.at||b.prefixToAdd?r.destination+"/"+(b.at||b.prefixToAdd):r.destination,".zip"===path.extname(b.url)?e(b,a):fs.stat(b.url,function(d,g){d?a(d):g.isDirectory()?k(b,a):g.isFile()?t(b,a):a(Error("Don't know how to handle '"+b.url+"'"))})):setImmediate(a)}function e(b,a){log.verbose("generate#_porcessZipFile()","processing:",b.url);async.series([function(d){if("http"===b.url.substr(0,4)){var a=path.join(h.getAppDir(),"templates/built-in",path.basename(b.url)),c=path.join(h.getPath(),"download",
path.basename(b.url));if(fs.existsSync(a))b.url=a,setImmediate(d);else if(fs.existsSync(c)){var m=fs.statSync(c);request.head(b.url,function(a,g){a||200!=g.statusCode||m.size!=g.headers["content-length"]||(b.url=c);setImmediate(d)})}else setImmediate(d)}else setImmediate(d)}.bind(l),function(a){try{log.verbose("generate#_fetchFile()","download path :",b.url);var d=b.url,c=path.join(h.getPath(),"download");fs.existsSync(d)?setImmediate(a):"http"!==d.substr(0,4)?setImmediate(a,Error("Source '"+d+"' does not exists")):
(fs.existsSync(c)||mkdirp(c),b.url=path.join(c,path.basename(b.url)),request(d).pipe(fs.createWriteStream(b.url).on("close",a)))}catch(u){log.error("Generate#_fetchFile()",u),setImmediate(a,u)}}.bind(l),function(a){log.verbose("generate#_extractZip()","destination:",b.at);b.at?fs.existsSync(b.url)?extract(b.url,{dir:b.at},a):setImmediate(a,Error("Cannot find the archive file : "+b.url)):setImmediate(a)}.bind(l)],a)}function k(b,a){log.verbose("generate#_processFolder()","Processing:",b.url);async.series([mkdirp.bind(null,
b.at),async.forEachSeries.bind(l,shelljs.ls("-R",b.url),function(a,c){fs.lstatSync(b.url+"/"+a).isFile()?(mkdirp.sync(path.dirname(b.at+"/"+a)),shelljs.cp("-f",b.url+"/"+a,b.at+"/"+a),async.forEachSeries(r.substitutions||[],function(d,c){if((new RegExp(d.fileRegexp)).test(a))w(b.at+"/"+a,d,c);else return setImmediate(c)},c)):setImmediate(c)})],function(b){setImmediate(a,b)})}function t(a,c){log.verbose("generate#_processFile()","Processing:",a.url);mkdirp.sync(a.at);shelljs.cp("-f",a.url,a.at);async.forEachSeries(r.substitutions||
[],function(b,c){if((new RegExp(b.fileRegexp)).test(file))w(a.at+"/"+file,b,c);else return setImmediate(c)},c)}function w(a,c,d){function b(a,b,c,d){log.verbose("_applyJsonSubstitutions()","json:",b,"in",a);async.waterfall([fs.readFile.bind(null,a,{encoding:"utf8"}),function(d,v){d=JSON.parse(d);var e;Object.keys(b).forEach(function(a){if(d.hasOwnProperty(a)||c&&c[a])d[a]=b[a],e=!0});e?fs.writeFile(a,JSON.stringify(d,null,2),{encoding:"utf8"},v):setImmediate(v)}],d)}function e(a,b,c){log.verbose("_applyVarsSubstitutions()",
"variables in",a);async.waterfall([fs.readFile.bind(null,a,{encoding:"utf8"}),function(c,d){Object.keys(b).forEach(function(a){c=c.replace("${"+a+"}",b[a])});fs.writeFile(a,c,{encoding:"uft8"},d)}],c)}function f(a,b,c){log.verbose("_applyRegexpSubstitutions()","word in",a);async.waterfall([fs.readFile.bind(null,a,{encoding:"utf8"}),function(c,d){Object.keys(b).forEach(function(a){c=c.replace(new RegExp(a,"g"),b[a])});fs.writeFile(a,c,{encoding:"utf8"},d)}],c)}log.verbose("_substitue()","file:",a);
async.series([function(d){c.json?b(a,c.json,c.add,d):setImmediate(d)},function(b){c.vars?e(a,c.vars,b):setImmediate(b)},function(b){c.regexp?f(a,c.regexp,b):setImmediate(b)}],d)}log.verbose("generate()","options:",a);var l=this,r={substitutions:p,destination:a.dstPath};async.series([async.forEachSeries.bind(l,a.tmplNames,q)],c)}};"undefined"!==typeof module&&module.exports&&(module.exports=new n)})();
