var util=require("util"),async=require("async"),path=require("path"),npmlog=require("npmlog"),request=require("request"),luna=require("./luna"),streamBuffers=require("stream-buffers"),spawn=require("child_process").spawn,fs=require("fs"),novacom=require("./novacom"),server=require("./server"),sdkenv=require("./sdkenv"),installer=require("./install"),launcher=require("./launch"),platformOpen={win32:["cmd","/c","start"],darwin:["open"],linux:["xdg-open"]},defaultAppInsptPort="9998",defaultNodeInsptPort=
"8080",defaultServiceDebugPort="5885";
(function(){var f=npmlog;f.heading="inspector";f.level="warn";var n={log:f,inspect:function(a,n,k){function l(b,d){var c=util.format("netstat -ltn 2>/dev/null | grep :%s | wc -l",b);async.series([a.session.run.bind(a.session,c,process.stdin,function(a){a=Buffer.isBuffer(a)?a.toString().trim():a.trim();if("0"===a)d(null,b);else if("1"===a)b=Number(b)+1,l(b,d);else return d(Error("Failed to get Debug Port"))},process.stderr)],function(a,c){a&&d(a)})}if("function"!==typeof k)throw Error("Missing completion callback (next="+
util.inspect(k)+")");a.svcDbgInfo={};a&&a.hasOwnProperty("serviceId")&&(a.serviceId instanceof Array?a.serviceId.forEach(function(b){a.svcDbgInfo[b]={}}):a.svcDbgInfo[a.serviceId]={});async.series([function(b){(new sdkenv.Env).getEnvValue("BROWSER",function(d,c){a.bundledBrowserPath=c;b()})},function(b){if(!a.serviceId)return b();installer.list(a,function(d,c){c instanceof Array&&(a.instPkgs=c);b(d)})},function(b){a.nReplies=1;a.session=new novacom.Session(a.device,b)},function(b){f.verbose("inspector#inspect()#_runApp");
if(!a.appId||a.running)return b();launcher.listRunningApp(a,null,function(d,c){c=[].concat(c);var g=c.map(function(a){return a.id});f.verbose("inspector#inspect()#_runApp#runAppIds",g.join(","));-1===g.indexOf(a.appId)?(f.verbose("inspector#inspect()#_runApp#launch",a.appId),launcher.launch(a,a.appId,{},b)):b()})},function(b){a.appId?a.session.forward(defaultAppInsptPort,a.hostPort||0,a.appId,b):b()},function(b){if(a.appId){var d=function(c,e){c?process.exit(1):e&&e.msg&&a.open&&server.openBrowser("http://localhost:"+
e.port+"/ares_cli/ares.html",a.bundledBrowserPath)},c=function(a,e){"@@ARES_CLOSE@@"===a?(e.status(200).send(),m=setTimeout(function(){process.exit(0)},2E3)):"@@GET_URL@@"===a&&(clearTimeout(m),e.status(200).send(g))},g="http://localhost:"+a.session.getLocalPortByName(a.appId),m;a.session.target.noPortForwarding&&(f.verbose("inspector#inspect()","noPortForwarding"),g="http://"+a.session.target.host+":9998");var e=[{reqPath:"/pagelist.json",propName:"inspectorUrl"},{reqPath:"/json/list",propName:"devtoolsFrontendUrl"}];
async.whilst(function(){return 0<e.length},function(c){listFile=e.pop();if(!listFile)return c();request.get(g+listFile.reqPath,function(b,p,d){if(b||200!==p.statusCode)return c();b=JSON.parse(d);for(var h in b)if(-1!=b[h].url.indexOf(a.appId)||-1!=b[h].url.indexOf(a.localIP)){if(!b[h][listFile.propName])return c(Error("Web inpector is already connected with the another browser. Please close the previous connection."));g+=b[h][listFile.propName];e=[];break}c()})}.bind(this),function(a){if(a)return b(a);
console.log("Application Debugging - "+g);server.runServer(__dirname,0,c,d)})}b()},function(b){var d=Object.keys(a.svcDbgInfo).filter(function(a){return"undefined"!==a});async.forEachSeries(d,function(c,b){if(!c)return b();var d=defaultServiceDebugPort;async.waterfall([function(b){a.instPkgs&&a.instPkgs.every(function(b){return-1!==c.indexOf(b.id)?(a.svcDbgInfo[c].path=path.join(path.dirname(b.folderPath),"..","services",c).replace(/\\/g,"/"),!1):!0});if(!a.svcDbgInfo[c].path)return b(Error("Failed to get service installation path '"+
c+"'"));b()},function(b){var e=path.join(a.svcDbgInfo[c].path,"services.json").replace(/\\/g,"/"),d;async.series([a.session.run.bind(a.session,"cat "+e,process.stdin,function(a){d=Buffer.isBuffer(a)?a.toString().trim():a.trim();b(null,d)},process.stderr)],function(a,e){if(a)return b(Error("Failed to find an installed service '"+c+"'"))})},function(a,b){try{if("native"===JSON.parse(a).engine)return b(Error(c+" is a native service, please use ares-gdbserver to debug it."));b()}catch(h){b(h)}},function(b){a.nReplies=
1;luna.send(a,{service:c,method:"quit"},{},function(a,c){b()},b)},function(b){a.session.runNoHangup("mkdir -p "+a.svcDbgInfo[c].path+"/_ares",b)},l.bind(this,d),function(b,f){d=b;a.session.runNoHangup("echo "+d+" > "+a.svcDbgInfo[c].path+"/_ares/debugger-port",f)},function(a){setTimeout(function(){a()},1E3)}.bind(this),function(b){a.svcDbgInfo[c].port=d;a.nReplies=1;luna.send(a,{service:c,method:"info"},{},function(a,c){b()},b)}.bind(this),function(a){setTimeout(function(){a()},1E3)}.bind(this),a.session.forward.bind(a.session,
defaultNodeInsptPort,a.hostPort||0,c),function(b){a.session.runNoHangup("rm -rf "+a.svcDbgInfo[c].path+"/_ares",b)},function(b,c){if(!a.svcDbgInfo[b].port)return c();var d,e=a.session.getLocalPortByName(b),f;d=util.format("http://%s:%s/debug?port=%s","localhost",e,a.svcDbgInfo[b].port);request.get(d,function(b,e,g){b||200!=e.statusCode||(console.log("nodeInsptUrl:",d),server.runServer(__dirname,0,function(a,b){"@@ARES_CLOSE@@"===a?(b.status(200).send(),f=setTimeout(function(){process.exit(0)},2E3)):
"@@GET_URL@@"===a&&(clearTimeout(f),b.status(200).send(d))},function(b,c){b?process.exit(1):c&&c.msg&&a.open&&server.openBrowser("http://localhost:"+c.port+"/ares_cli/ares.html",a.bundledBrowserPath)}),c())})}.bind(this,c)],function(a,c){f.verbose("inspector#inspect()","err: ",a,"results:",c);b(a,c)})},function(a){b(a)})},function(a){f.verbose("inspector#inspect()","running...");setImmediate(a)}],function(a,d){f.verbose("inspector#inspect()","err: ",a,"results:",d);setImmediate(k,a)})}};"undefined"!==
typeof module&&module.exports&&(module.exports=n)})();
