var fs=require("fs"),path=require("path"),util=require("util"),npmlog=require("npmlog"),async=require("async"),streamBuffers=require("stream-buffers"),crypto=require("crypto"),luna=require("./luna"),novacom=require("./novacom"),appdata=require("./cli-appdata"),errMsgHndl=require("./error-handler");
(function(){function q(a,b){var d=[{idx:0,name:"internal",dvid:null,drid:null,type:"flash",uri:"/media/developer"}],c=a.session.getDevice().lunaAddr.getStorageList;if(!c)return b(null,d);var f=c.returnValue.split(".");luna.send(a,c,{subscribe:!1},function(a,c){var b=a;for(index=1;index<f.length;index++)b=b[f[index]];!0===b.returnValue&&b.devices&&b.devices.filter(function(a){return"usb"===a.deviceType}).forEach(function(a){a.subDevices.forEach(function(b){d.push({idx:d.length,name:"usb"+d.length,
dvid:a.deviceId,drid:b.deviceId,type:"usb",uri:b.deviceUri})})});c(null,d)},function(a,c){if(a&&-1!==a.toString().indexOf("not exist"))return b(null,d);b(a,c)})}var b=npmlog;b.heading="installer";b.level="warn";var t=new appdata,v={log:b,install:function(a,e,d){if("function"!==typeof d)throw Error("Missing completion callback (next="+util.inspect(d)+")");var c=path.basename(e),f={tempDirForIpk:"/media/developer/temp",changeTempDir:!0,removeIpkAfterInst:!0},n=t.getConfig(!0);if(n.install)for(prop in n=
n.install,n)f.hasOwnProperty(prop)&&(f[prop]=n[prop]);if(c){var h=path.join(f.tempDirForIpk,c).replace(/\\/g,"/"),r=new streamBuffers.WritableStreamBuffer,u=a.appId,k,l,p=200,m;b.info("installer#install():","installing "+e);a=a||{};async.waterfall([function(g){a.nReplies=0;new novacom.Session(a.device,g)},function(g,b){a.session=g;setImmediate(b,null,a)},q,function(g,b){var d=g.map(function(a){return a.name});if(a.storage&&-1===d.indexOf(a.storage))return setImmediate(b,Error("invalid storage name"));
g.forEach(function(b){b.name===a.storage&&(m=b)});m&&f.changeTempDir&&(f.tempDirForIpk=path.join(m.uri,"temp").replace(/\\/g,"/"),h=path.join(f.tempDirForIpk,c).replace(/\\/g,"/"));setImmediate(b)},function(b){if(a.opkg&&"root"!=a.session.getDevice().username)return setImmediate(b,Error("opkg-install is only available for the device allowing root-connection"));var g="/bin/rm -rf "+f.tempDirForIpk+" && /bin/mkdir -p "+f.tempDirForIpk;"root"===a.session.getDevice().username&&(g+=" && /bin/chmod 777 "+
f.tempDirForIpk);a.op=(a.session.target.files||"stream")+"Put";a.session.run(g,null,null,null,b)},function(b){console.log("Installing package "+e);a.session.put(e,h,b)},function(b){a.session.run('/bin/ls -l "'+h+'"',null,r,null,b)},function(a){b.verbose("installer#install():","ls -l:",r.getContents().toString());a()},function(a){var c=crypto.createHash("md5"),d=new Buffer(p),g=0;async.waterfall([fs.lstat.bind(fs,e),function(a,b){a.size>p?g=a.size-p:(g=0,p=a.size);b()},fs.open.bind(fs,e,"r"),function(a,
b){fs.read(a,d,0,p,g,function(a,g){c.update(d);b()})},function(){(k=c.digest("hex"))||b.warn("installer#install():","Failed to get md5sum from the ipk file");b.verbose("installer#install():","srcMd5:",k);a()}],function(b){a(b)})},function(c){function d(a){if(a=Buffer.isBuffer(a)?a.toString().trim():a.trim())l=a.split("-")[0].trim(),b.verbose("installer#install():","dstMd5:",l);l||b.warn("installer#install():","Failed to get md5sum from the transmitted file");c()}var g="/usr/bin/tail -c "+p+' "'+h+
'" | /usr/bin/md5sum';async.series([function(b){a.session.run(g,null,d,null,b)}],function(a){if(a)return c(a)})},function(a){if(k&&l){if(b.verbose("installer#install():","srcMd5:",k,", dstMd5:",l),k!==l)return a(Error("File transmission error, please try again."))}else b.warn("installer#install():","Cannot verify transmitted file");a()},function(c){function d(b){function c(a){a=Buffer.isBuffer(a)?a.toString():a;console.log(a)}var d='/usr/bin/opkg install "'+h+'"',d=d.concat(a.opkg_param?" "+a.opkg_param:
"");async.series([a.session.run.bind(a.session,d,null,c,c),a.session.run.bind(a.session,"/usr/sbin/ls-control scan-services ",null,null,c)],function(a){if(a)return b(a);b(null,null)})}function g(c){var d=a.session.getDevice(),g=d.lunaAddr.install,k=g.returnValue.split("."),f="webos3"===d.type?{target:h,subscribe:!0}:{id:u,ipkUrl:h,subscribe:!0};"webos3"!==d.type&&m&&m.dvid&&m.drid&&(f.target={deviceId:m.dvid,driveId:m.drid});luna.send(a,g,f,function(a,d){b.verbose("installer#install():","lineObj: %j",
a);var c=a;for(index=1;index<k.length;index++)c=c[k[index]];c.match(/FAILED/i)?(b.verbose("installer#install():","failure"),a.details&&a.details.errorCode?d(errMsgHndl.getErrMsg(g.service,a.details.errorCode)||c):d(c)):c.match(/installed|^SUCCESS/i)?(b.verbose("installer#install():","success"),d(null,c)):(b.verbose("installer#install():","waiting"),d(null,null))},c)}op=a.opkg?d:g;op(c)},function(b,c){"function"===typeof b&&(c=b);f.removeIpkAfterInst?a.session.run('/bin/rm -f "'+h+'"',null,null,null,
c):c()},function(b){a.session.end();a.session=null;b(null,{msg:"Success"})}],function(a,c){b.verbose("installer#waterfall callback err:",a);d(a,c)})}else d(Error("Invalid package: '"+e+"'"))},remove:function(a,e,d){if("function"!==typeof d)throw Error("Missing completion callback (next="+util.inspect(d)+")");a=a||{};async.waterfall([function(b){a.nReplies=void 0;a.session=new novacom.Session(a.device,b)},function(b,d){a.session=b;if(a.opkg&&"root"!=a.session.getDevice().username)return setImmediate(d,
Error("opkg-remove is only available for the device allowing root-connection"));setImmediate(d)},function(c){function d(b){function d(a){a=Buffer.isBuffer(a)?a.toString():a;return b(Error(a))}var c="/usr/bin/opkg remove "+e,c=c.concat(a.opkg_param?" "+a.opkg_param:"");async.series([a.session.run.bind(a.session,c,null,function(a){a=Buffer.isBuffer(a)?a.toString():a;console.log(a);if(a.match(/No packages removed/g))return b(Error("[package Name: "+e+"] "+a))},d),a.session.run.bind(a.session,"/usr/sbin/ls-control scan-services ",
null,null,d)],function(a){if(a)return b(a);b(null,{})})}function n(c){var d=a.session.getDevice(),f=d.lunaAddr.remove,h=f.returnValue.split("."),l=0;luna.send(a,f,"webos3"===d.type?{subscribe:!0,packageName:e}:{id:e,subscribe:!0},function(a,d){b.verbose("installer#remove():","lineObj: %j",a);var c=a;for(index=1;index<h.length;index++)c=c[h[index]];c.match(/FAILED/i)?(b.verbose("installer#remove():","failure"),l++||d(Error(c))):c.match(/removed|^SUCCESS/i)?(b.verbose("installer#remove():","success"),
d(null,{status:c})):(b.verbose("installer#remove():","waiting"),d())},c)}op=a.opkg?d:n;op(c)}],function(a,f){b.verbose("installer#remove():","err:",a,"result:",f);a||(f.msg="Removed package "+e);d(a,f)})},list:function(a,e){if("function"!==typeof e)throw Error("Missing completion callback (next="+util.inspect(e)+")");a=a||{};async.waterfall([function(b){a.nReplies=1;a.session=new novacom.Session(a.device,b)},function(b,c){a.session=b;if(a.opkg&&"root"!=a.session.getDevice().username)return setImmediate(c,
Error("opkg-list is only available for the device allowing root-connection"));setImmediate(c)},function(d){function c(b){function c(a){a=Buffer.isBuffer(a)?a.toString():a;console.log(a)}var d;d="/usr/bin/opkg list".concat(a.opkg_param?" "+a.opkg_param:"");async.series([a.session.run.bind(a.session,d,null,c,c)],function(a){if(a)return b(a);b(null,{})})}function f(c){var d=a.session.getDevice().lunaAddr.list,f=d.returnValue.split(".");luna.send(a,d,{subscribe:!1},function(a,c){for(var d=a,e=1;e<f.length;e++)d=
d[f[e]];if(Array.isArray(d)){if(!t.compareProfileSync("signage"))for(var e=0;e<d.length;e++)d[e].visible||(d.splice(e,1),e--);b.verbose("installer#list():","success");c(null,d)}else b.verbose("installer#list():","failure"),c(Error("object format error"))},c)}op=a.opkg?c:f;op(d)}],function(a,c){b.verbose("installer#list():","err:",a,"results:",c);e(a,c)})},listStorage:function(a,e){if("function"!==typeof e)throw Error("Missing completion callback (next="+util.inspect(e)+")");a=a||{};async.waterfall([function(b){a.nReplies=
1;a.session=new novacom.Session(a.device,b)},function(b,c){a.session=b;setImmediate(c,null,a)},q],function(a,c){b.verbose("installer#listStorage():","err:",a,"results:",c);e(a,c)})}};"undefined"!==typeof module&&module.exports&&(module.exports=v)})();
