var async=require("async"),child_process=require("child_process"),fs=require("fs"),log=require("npmlog"),net=require("net"),path=require("path"),shelljs=require("shelljs"),stream=require("stream"),Validator=require("jsonschema").Validator;
(function(){function l(b){log.silly("NovacomDB#_getNovacomPath()");var a="novacom";"undefined"!==typeof b&&!0===b&&(a="novacomd");if("undefined"===typeof l[a]){var g="win32"===process.platform?a+".exe":a;b=path.resolve(__dirname,"..","bin",g);g=path.resolve(__dirname,"..",a,process.platform,g);fs.existsSync(b)?l[a]=b:fs.existsSync(g)?l[a]=g:log.verbose("No "+a+" in path ("+b+", "+g+")")}log.verbose("NovacomDB#_getNovacomPath()#",a,l[a]);return l[a]}function u(b){log.verbose("NovacomUSB#_getFreePort()");
var a=net.createServer();a.on("error",function(a){log.info("NovacomUSB#_getFreePort()","error!");return setImmediate(b,a)});a.listen(0,function(){port=a.address().port;a.close(function(){log.info("NovacomUSB#_getFreePort()","port",port);return setImmediate(b,null,port)})})}function q(b,a,g){log.verbose("NovacomUSB#_checkSchema()","data:",b,"schemaFile",a);var h="/"+path.basename(a).split(".")[0],c={id:"test",type:"array",items:{$ref:h+"Schema"}};if(fs.statSync(a).isFile()){var k=fs.readFileSync(a,
"utf8"),f,d,e,r=new Validator;try{d=JSON.parse(k);r.addSchema(d,h);if((f=r.validate(b,c))&&0<f.errors.length){e="";e=e.concat("Invalid data! schema:",a);for(idx in f.errors){e=e.concat("\n");var p=f.errors[idx].property+" "+f.errors[idx].message;null!==(f=/instance\[*.*\]*\./g.exec(p))&&(p=p.substring(f[0].length));e=e.concat(p)}log.info("NovacomUSB#_checkSchema()","error!");return setImmediate(g,Error(e))}return setImmediate(g,null,b)}catch(n){return log.info("NovacomUSB#_checkSchema()","error!"),
setImmediate(g,Error("Invalid JSON Schema"))}}else return log.verbose("Resolver#save()#_checkSchema()",a,"is not exist!"),setImmediate(g,null,b)}var m={};"undefined"!==typeof module&&module.exports&&(module.exports=m);log.heading="novacom-usb";log.level="verbose";m.log=log;var t=function(b,a){log.verbose("NovacomUSB#_getNovacomDeviceList()","options",b);async.parallel({keys:function(a){var b=path.resolve(process.env.HOME||process.env.USERPROFILE,".ssh"),c=path.resolve(__dirname,"setting-files","keys");
if(!fs.existsSync(c))return a();fs.readdir(c,function(h,f){if(h)return a(h);f.forEach(function(d){fs.existsSync(path.join(b,d))||shelljs.cp("-rf",path.join(c,d),b)});a()})},auths:function(a){var h=path.join(b.appdir,"novacom-usb-auth.json"),c=path.resolve(__dirname,"setting-files","novacom-usb-auth.json");if(!fs.existsSync(c))return a();fs.existsSync(h)||shelljs.cp("-rf",c,b.appdir);log.verbose("Resolver#load#_readFile()","<<< "+h);fs.readFile(h,"utf8",function(c,f){if(c&&"ENOENT"===c.code)return setImmediate(a,
null,[]);var d=JSON.parse(f);return Array.isArray(d)?setImmediate(q,d,path.join(__dirname,"schema/NovacomUSBAuth.schema"),a):(log.info("NovacomUSB#_getNovacomDeviceList()","error"),setImmediate(a,Error("Incorrect file format.")))})},devices:function(a){var b=new net.Socket,c,g="";b.on("error",function(a){c=a});b.on("close",function(){if("undefined"!==typeof c)return log.info("Novacomd daemon is not running ...!",c),setImmediate(a,null,[]);var b=[],d,e,h,k,n;n=g.split("\n");for(e in n)if(0!==n[e].trim().length){d=
n[e].split(" ");if(5===d.length||6===d.length)k=d[4].split(":"),2===k.length&&k[1]&&(h=parseInt(k[0]));d="undefined"!==typeof h&&d[5]?{order:-1,profile:"watch",index:e,id:d[1],name:d[2],type:d[3],transport:d[2],device_mode:d[5],description:"",host:"127.0.0.1",port:h,files:"stream",noPortForwarding:!1,indelible:!0,conn:["novacom","ssh"]}:{order:-1,profile:"watch",index:e,id:d[1],name:d[2],type:d[3],transport:d[2],description:"",host:"127.0.0.1",port:void 0,files:"stream",noPortForwarding:!1,indelible:!0,
conn:["novacom"]};"usb"===d.transport.slice(0,3)&&(d.type="w2-linux");b.push(d)}return setImmediate(q,b,path.join(__dirname,"schema/NovacomUSBDevice.schema"),a)});b.on("data",function(a){g+=a.toString();b.end()});return b.connect({port:6968})}},function(b,h){var c,g,f,d={},e=h.devices;if(b)return log.info("NovacomUSB#_getNovacomDeviceList()","err",b),setImmediate(a,b);for(c in h.auths)d[h.auths[c].id]=h.auths[c];for(c in e)g=e[c].id,f="root"===e[c].device_mode?"*"+e[c].type+"-root*":"developer"===
e[c].device_mode?"*"+e[c].type+"-developer*":"*"+e[c].type+"*",d.hasOwnProperty(g)?(d[g].hasOwnProperty("username")&&(e[c].username=d[g].username),d[g].hasOwnProperty("password")&&(e[c].password=d[g].password),d[g].hasOwnProperty("privateKey")&&(e[c].privateKey=d[g].privateKey)):d.hasOwnProperty(f)&&(d[f].hasOwnProperty("username")&&(e[c].username=d[f].username),d[f].hasOwnProperty("password")&&(e[c].password=d[f].password),d[f].hasOwnProperty("privateKey")&&(e[c].privateKey=d[f].privateKey));return setImmediate(a,
null,e)})},v=function(b,a,g){b=l()+" run file:///usr/bin/which "+a+" -d "+b;child_process.exec(b,{encoding:"utf8",timeout:1E3,maxBuffer:204800,killSignal:"SIGTERM",cwd:null,env:null},function(a,b,k){var c;b&&(c=b.toString());setImmediate(g,a,c)}).stdin.end()};m.getDeviceList=t;m.connectTunnel=function(b,a){if("undefined"!==typeof b.port||"usb"!==b.transport)return setImmediate(a,null,b);u(function(g,h){var c=l()+" -P -f "+h+":10022 -d "+b.id;child_process.exec(c,{encoding:"utf8",timeout:1E3,maxBuffer:204800,
killSignal:"SIGTERM",cwd:null,env:null},function(a,b,c){});b.port=h;return setImmediate(a,null,b)})};m.waitDeviceConnect=function(b,a){log.verbose("NovacomUSB#_waitDeviceConnect()","options",b);if(!1===("object"===typeof b&&"boolean"===typeof b.waitForDevice?b.waitForDevice:!1))return setImmediate(a);var g=!0,h=0,c,k=setInterval(function(){t(b,function(b,e){if(b)return setImmediate(a,b);Array.isArray(e)&&e.forEach(function(b){c=b.transport;if("usb"===c.slice(0,3)||"tcp"===c.slice(0,3))process.stdout.write("\b \n\r"),
clearInterval(k),setImmediate(a)});0==e.length&&1==g&&(process.stdout.write("\nwaiting for device...."),g=!1)});if(0==g){var f=h++%3;0===f?process.stdout.write("\b/"):1===f?process.stdout.write("\b-"):process.stdout.write("\b\\")}},200)};m.getNovacomPath=l;m.getNovacomDaemonPath=function(){return l(!0)};m.getNovacomUser=function(b,a){var g=l()+' run "file:///usr/bin/id -un" -d '+b;child_process.exec(g,{encoding:"utf8",timeout:1E3,maxBuffer:204800,killSignal:"SIGTERM",cwd:null,env:null},function(b,
c,g){var f;c&&(f=c.toString());setImmediate(a,b,f)}).stdin.end()};m.runDeviceCommand=function(b,a,g,h,c,k){var f={},d={};h?h instanceof stream.Stream?(log.silly("Session#run()","stdout: stream"),f.stdout=h.write,d.stdout=h):h instanceof Function?(log.silly("Session#run()","stdout: function"),f.stdout=h):setImmediate(k,Error("Invalid novacom stdout: "+util.inspect(h))):(log.silly("Session#run()","stdout: none"),f.stdout=function(){});c?c instanceof stream.Stream?(log.silly("Session#run()","stderr: stream"),
f.stderr=c.write,d.stderr=c):c instanceof Function?(log.silly("Session#run()","stderr: function"),f.stderr=c):setImmediate(k,Error("Invalid novacom stderr: "+util.inspect(c))):(log.silly("Session#run()","stderr: none"),f.stderr=function(){});a=a.replace(/\"/g,'\\"');var e;async.series([function(c){e=" run file://";"/"!==a[0]?(cmdTokens=a.split(" "),v(b,cmdTokens[0],function(b,d){if(!d)return setImmediate(c,Error("Unable to run "+cmdTokens[0]));cmdTokens[0]=d;a=cmdTokens.join(" ");e+=a;c()})):(e+=
a,c())},function(b){var a=child_process.spawn(l(),[e],{stdio:["ignore","pipe","pipe"]});a.stderr.on("data",function(a){f.stderr.bind(d.stderr)(a)});a.stdout.on("data",function(a){f.stdout.bind(d.stdout)(a)});a.on("exit",function(a){setImmediate(b)})}],function(a){setImmediate(k,a)})}})();
