var fs=require("fs"),path=require("path"),util=require("util"),stream=require("stream"),net=require("net"),mkdirp=require("mkdirp"),async=require("async"),log=require("npmlog"),ssh2=require("ssh2"),shelljs=require("shelljs"),express=require("express"),http=require("http"),mkdirp=require("mkdirp"),request=require("request"),Validator=require("jsonschema").Validator,server=require("./server"),errMsgHndl=require("./error-handler"),appdata=require("./cli-appdata"),novacomusb=require("./novacom-usb");
(function(){function p(a,b,c){var d=null;if(0!==b||c)d=Error("Command '"+a+"' exited with code="+b+" (signal: "+c+")"),d.code=b,d.signal=c;return d}function q(){this.devices=[];this.deviceFileContent=null;l=new appdata;r=l.getPath()}var m={};"undefined"!==typeof module&&module.exports&&(module.exports=m);log.heading="novacom";log.level="warn";m.log=log;var h=path.resolve(process.env.HOME||process.env.USERPROFILE,".ssh"),r,l;m.Resolver=q;m.Resolver.prototype={load:function(a){var b=this;log.verbose("Resolver#load()");
async.waterfall([function(a){log.verbose("Resolver#load#_replaceBuiltinSshKey()");var b=path.join(__dirname,"webos_emul"),c=path.join(h,"webos_emul");fs.stat(b,function(d,e){d?"ENOENT"===d.code?setImmediate(a):setImmediate(a,d):fs.stat(c,function(d,f){d?"ENOENT"===d.code?mkdirp(h,function(d){shelljs.cp("-rf",b,h);fs.chmodSync(c,"0600");setImmediate(a)}):setImmediate(a,d):(e.mtime.getTime()>f.mtime.getTime()&&(shelljs.cp("-rf",b,h),fs.chmodSync(c,"0600")),setImmediate(a))}.bind(this))}.bind(this))}.bind(b),
function(a){var c=l.getDeviceList(!0);Array.isArray(c)?(log.silly("Resolver#load#_loadString()","inDevices:",c),async.forEach(c,function(a,c){async.series([b._loadOne.bind(b,a),b._addOne.bind(b,a)],c)},function(c,d){c?setImmdiate(a,c):(log.verbose("Resolver#load#_loadString()","devices:",b.devices),setImmediate(a))})):setImmediate(a,Error("Incorrect file format'"))}.bind(b),function(a){log.silly("Resolver#load#_loadUSBDevice()");async.waterfall([novacomusb.getDeviceList.bind(novacomusb,{appdir:r}),
function(a,c){async.forEach(a,function(a,c){async.series([b._loadOne.bind(b,a),b._addOne.bind(b,a)],c)},c)}],function(b,c){setImmediate(a,b)})}.bind(b)],function(c){c?setImmediate(a,c):(log.info("Resolver#load()","devices:",b.devices),setImmediate(a))})},_loadOne:function(a,b){log.silly("Resolver#_loadOne()","device:",a);"string"===typeof a.privateKey?(a.privateKeyName=a.privateKey,a.privateKey=new Buffer(a.privateKey,"base64"),setImmediate(b)):"object"===typeof a.privateKey&&"string"===typeof a.privateKey.openSsh?
(a.privateKeyName=a.privateKey.openSsh,async.waterfall([fs.readFile.bind(this,path.join(h,a.privateKey.openSsh),b),function(b,d){a.privateKey=b;setImmediate(d)}],function(c){c&&(log.verbose("Resolver#_loadOne()","Unable to find SSH private key named '"+a.privateKey.openSsh+"' from '"+h+" for '"+a.name+"'"),a.privateKey=void 0);setImmediate(b)})):"webospro"===typeof a.type?setImmediate(b,Error("Not implemented: go & grab the webOS Pro private key here")):(a.password||log.verbose("Resolver#_loadOne()",
"Regist privateKey : need to set a SSH private key in "+h+" for'"+a.name+"'"),a.privateKeyName=void 0,a.privateKey=void 0,setImmediate(b))},_addOne:function(a,b){if(!a.profile||!l.compareProfileSync(a.profile))return setImmediate(b);a.display={name:a.name,type:a.type,privateKeyName:a.privateKeyName,passphase:a.passphase,description:a.description,conn:a.conn||["ssh"],devId:a.id||null};a.username&&a.host&&a.port&&(a.display.addr="ssh://"+a.username+"@"+a.host+":"+a.port);for(var c in a)"display"!==
c&&(a.display[c]=a[c]);log.silly("Resolver#_addOne()","device:",a);this.devices=this.devices.filter(function(b){return b.name!==a.name});c=l.getCommandService();a.lunaSend=c[a.type].lunaSend;a.lunaAddr=c[a.type].lunaAddr;this.devices.push(a);setImmediate(b)},save:function(a,b){log.verbose("Resolver#save()","devicesData:",a);return l.setDeviceList(a,b)},list:function(a){log.verbose("Resolver#list()");setImmediate(a,null,this.devices.map(function(a){return a.display}))},setDefaultName:function(a,b){var c=
"string"===typeof a?a:a&&a.name;if(!c){c=this.devices.filter(function(a){return a.conn&&-1!==a.conn.indexOf("novacom")});if(1<c.length)return b(Error("multiple devices are connected by novacom, please specify target name."));c=0<c.length&&c[0].name?c[0].name:"emulator"}b(null,"name",c)},getDeviceBy:function(a,b,c){log.verbose("Resolver#getDeviceBy()","key:",a,"value:",b);var d=this.devices.filter(function(c){return c[a]&&c[a]===b});if(1>d.length)setImmediate(c,Error("No device matching '"+a+"'='"+
b+"'"));else if(log.verbose("Resolver#getDeviceBy()","devices:",d),"function"===typeof c)log.silly("Resolver#getDeviceBy()","async"),setImmediate(c,null,d[0]);else return log.silly("Resolver#getDeviceBy()","sync"),d[0]},getSshPrvKey:function(a,b){var c="string"===typeof a?a:a&&a.name;c?async.waterfall([this.getDeviceBy.bind(this,"name",c),function(a,b){log.info("Resolver#getSshPrvKey()","target.host:",a.host);var c="http://"+a.host+":9991/webos_rsa",d=a.name.replace(/(\s+)/gi,"_")+"_webos",e=path.join(h,
d);request.head(c,function(a,f,k){if(a||f&&200!==f.statusCode)return setImmediate(b,Error("Failed to get ssh private key"));log.info("Resolver#getSshPrvKey()#head","content-type:",f.headers["content-type"]);log.info("Resolver#getSshPrvKey()#head","content-length:",f.headers["content-length"]);request(c).pipe(fs.createWriteStream(e)).on("close",function(a){if(a)return setImmediate(b,Error("Failed to get ssh private key"));setImmediate(b,a,e,d)})})},function(a,b,c){log.info("Resolver#getSshPrvKey()",
"SSH Private Key:",a);console.log("SSH Private Key:",a);fs.chmodSync(a,"0600");setImmediate(c,null,b)}],b):setImmediate(b,Error("Need to select a device name to get Ssh Private Key"))},modifyDeviceFile:function(a,b,c){var d,e=l.getDeviceList(!0);log.verbose("modifyDeviceFile()#op:",a,"#targt:",b);if(!b.name)return setImmediate(c,Error("Incorrect target name"));if(!Array.isArray(e))return setImmediate(c,Error("Incorrect file format'"));d=e.filter(function(a){var c=!1;b.name===a.name&&(b.profile?b.profile===
a.profile&&(c=!0):c=!0);return c});log.verbose("modifyDeviceFile()#matchedDevices:",d);if("add"==a){if(0<d.length)return setImmediate(c,Error("Existing Target Name"));for(key in b)"@DELETE@"===b[key]&&delete b[key];e=e.concat(b)}else if("remove"===a||"modify"===a){var f,g;if(0===d.length)return setImmediate(c,Error("There is no device named "+b.name));f=d.map(function(a){return a.name});"remove"===a?e=e.filter(function(a){return-1!==f.indexOf(a.name)?!0===a.indelible?(g=a.name+" is not removable",
!0):!1:!0}):"modify"===a&&(e=e.map(function(a){if(-1!==f.indexOf(a.name))for(prop in b)b.hasOwnProperty(prop)&&(a[prop]=b[prop],"@DELETE@"===a[prop]&&delete a[prop]);return a}));if(g)return setImmediate(c,Error(g))}else return setImmediate(c,Error("Unknown operator #"+a));this.save(e,c)}};m.Session=function(a,b){if("function"!==typeof b)throw Error("novacom.Session(): BUG next must be a common-js callback");log.info("novacom.Session()","opening session to '"+("string"===typeof a?a:a&&a.name)+"'");
this.resolver=new q;async.waterfall([this.resolver.load.bind(this.resolver),this.resolver.setDefaultName.bind(this.resolver,a),this.resolver.getDeviceBy.bind(this.resolver),this.checkConnection.bind(this),this.begin.bind(this)],b)};m.Session.prototype={checkConnection:function(a,b){var c=!1;if(a&&a.host&&a.port){var d=new net.Socket;d.setTimeout(2E3);var e=d.connect({host:a.host,port:a.port});e.on("connect",function(){c=!0;e.end();setImmediate(b,null,a)});e.on("error",function(a){e.destroy();setImmediate(b,
errMsgHndl.changeErrMsg(a))});e.on("timeout",function(a){e.destroy();c||setImmediate(b,errMsgHndl.changeErrMsg("Time out"))})}else setImmediate(b,null,a)},begin:function(a,b){function c(a){setImmediate(b,errMsgHndl.changeErrMsg(a),this)}function d(){log.verbose("Clear Session");e.end();setTimeout(function(){process.exit()},500)}log.verbose("Session#begin()","target:",a);var e=this;this.target=a||this.target;if(this.target.conn&&-1===this.target.conn.indexOf("ssh"))return setImmediate(b,null,this),
this;if(!typeof this.target.privateKey&&!typeof this.target.password)return setImmediate(b,Error("Private Key File or Password does not exist!!"));this.ssh||(this.forwardedPorts=[],this.ssh=new ssh2,this.ssh.on("connect",function(){log.verbose("Session#begin()","ssh session event: connected")}),this.ssh.on("ready",c.bind(this)),this.ssh.on("error",c.bind(this)),this.ssh.on("end",function(){log.verbose("Session#begin()","ssh session event: end")}),this.ssh.on("close",function(a){log.verbose("Session#begin()",
"ssh session event: close  (had_error:",a,")")}),this.target.readyTimeout=3E4,this.ssh.connect(this.target),process.on("SIGHUP",d),process.on("SIGINT",d),process.on("SIGQUIT",d),process.on("SIGTERM",d),process.on("exit",function(a){d()}));return this},getDevice:function(){return this.target},end:function(){log.verbose("Session#end()","user-requested termination");this.ssh&&this.ssh.end();return this},_checkSftp:function(a){this.ssh.subsys("sftp",function(b,c){if(b)return setImmediate(a,b);c.once("data",
function(b){if(b.toString().match(RegExp("sftp-server(.| )+not found","gi")))return b=Error("Unable to use sftp"),b.code=4,setImmediate(a,b)})})},put:function(a,b,c){log.verbose("Session#put()","uploding into device:",b,"from host:",a);var d,e=this;log.verbose("Session#put()","sftpPut() :: start");e.sftpPut(a,b,function(f){f?(log.verbose(f),4===f.code||127===f.code?(log.verbose("Session#put()","sftp is not available, attempt transfering file via streamPut"),d=fs.createReadStream(a),e.streamPut(b,
d,c)):(14===f.code&&(f=errMsgHndl.changeErrMsg("insufficient free space")),setImmediate(c,f))):(log.verbose("Session#put()","sftpPut() :: done"),setImmediate(c))})},streamPut:function(a,b,c){log.verbose("Session#streamPut()","streaming into device:"+a);this.run('/bin/cat > "'+a+'"',b,null,process.stderr,c)},sftpPut:function(a,b,c){log.verbose("Session#sftpPut()","host:"+a+" => device:"+b);var d=this;d._checkSftp(c);async.series({transfer:function(c){d.ssh.sftp(function(d,e){if(d)return setImmediate(c,
d);var f=fs.createReadStream(a),g=e.createWriteStream(b);g.on("close",function(){e.end();setImmediate(c)});g.on("exit",function(a,b){d=p("sftpPut",a,b);setImmediate(c,d)});g.on("error",function(a){log.verbose("Session#sftpPut()","error:",a);setImmediate(c,a)});f.pipe(g)})}},function(a){setImmediate(c,a)})},get:function(a,b,c){log.verbose("Session#get()","downloading into host:",b,"from target:",a);var d=this;log.verbose("Session#get()","sftpGet() :: start");d.sftpGet(a,b,function(e){e?(log.verbose(e),
4===e.code||127===e.code?(log.verbose("Session#get()","sftp is not available, attempt transfering file via streamPut"),os=fs.createWriteStream(b),d.streamGet(a,os,c)):setImmediate(c,e)):(log.verbose("Session#get()","sftpGet() :: done"),setImmediate(c))})},streamGet:function(a,b,c){log.verbose("Session#streamGet()","streaming from device:"+a);this.run("/bin/cat "+a,null,b,process.stderr,c)},sftpGet:function(a,b,c){log.verbose("Session#sftpGet()","target:"+a+" => host:"+b);var d=this;d._checkSftp(c);
async.series({transfer:function(c){d.ssh.sftp(function(d,e){if(d)setImmediate(c,d);else{var f=e.createReadStream(a),g=fs.createWriteStream(b);f.on("close",function(){e.end();setImmediate(c)});f.on("exit",function(a,b){d=p("sftpGet",a,b);setImmediate(c,d)});f.on("error",function(a){log.verbose("Session#sftpGet()","error:",a);setImmediate(c,a)});f.pipe(g)}})}},function(a){setImmediate(c,a)})},run:function(a,b,c,d,e){this.ssh?this.run_ssh(a,b,c,d,e):novacomusb.runDeviceCommand(this.target.id,a,b,c,d,
e)},run_ssh:function(a,b,c,d,e){log.verbose("Session#run()","cmd="+a);if("function"!==typeof e)throw Error("BUG: 'next' is not a callback");var f={},g={};c?c instanceof stream.Stream?(log.silly("Session#run()","stdout: stream"),f.stdout=c.write,g.stdout=c):c instanceof Function?(log.silly("Session#run()","stdout: function"),f.stdout=c):setImmediate(e,Error("Invalid novacom stdout: "+util.inspect(c))):(log.silly("Session#run()","stdout: none"),f.stdout=function(){});d?d instanceof stream.Stream?(log.silly("Session#run()",
"stderr: stream"),f.stderr=d.write,g.stderr=d):d instanceof Function?(log.silly("Session#run()","stderr: function"),f.stderr=d):setImmediate(e,Error("Invalid novacom stderr: "+util.inspect(d))):(log.silly("Session#run()","stderr: none"),f.stderr=function(){});this.ssh.exec(a,function(k,n){log.verbose("Session#run()","exec cmd: "+a+", err:"+k);if(k)return setImmediate(e,k);n.on("data",function(a,b){b=b||"stdout";log.verbose("Session#run()","on data ("+b+")");f[b].bind(g[b])(a)}).stderr.on("data",function(a){log.verbose("Session#run()",
"on data (stderr)");f.stderr.bind(g.stderr)(a)});n.on("end",function(){log.verbose("Session#run()","event EOF from (cmd: "+a+")");c!==process.stdout&&c instanceof stream.Stream&&c.end();d!==process.stderr&&d instanceof stream.Stream&&d.end()});n.on("exit",function(b,c){log.verbose("Session#run()","event exit code="+b+", signal="+c+" (cmd: "+a+")");k=p(a,b,c);setImmediate(e,k)});n.on("close",function(){log.verbose("Session#run()","event close  (cmd: "+a+")");void 0===k&&setImmediate(e)});b&&(b.pipe(n),
log.verbose("Session#run()","resuming input"))}.bind(this))},runNoHangup:function(a,b,c,d){this.ssh?this.runNoHangup_ssh(a,b,c,d):novacomusb.runDeviceCommand(this.target.id,a,null,null,null,d)},runNoHangup_ssh:function(a,b,c,d){log.verbose("Session#runNoHangup()","cmd="+a);if(2>arguments.length)throw Error("BUG: 'next' is not a callback");for(arg in arguments)"undefined"===typeof arguments[arg]&&(delete arguments[arg],arguments.length--);switch(arguments.length){case 2:d=b;b=c=null;break;case 3:d=
c,c=b,b=null}if("function"!==typeof d)throw Error("BUG: 'next' is not a callback");this.ssh.exec(a,function(e,f){log.verbose("Session#run()","exec cmd: "+a+", err:"+e);if(e)return setImmediate(d,e);f.on("data",function(a,c){var d=Buffer.isBuffer(a)?a.toString():a;log.verbose("[Session#runNoHangup()#onData]",d);b&&b(a)}).stderr.on("data",function(a){var c=Buffer.isBuffer(a)?a.toString():a;log.verbose("Session#runNoHangup()#onData#stderr#",c);b&&b(a)});if(c)f.on("exit",function(b,d){log.verbose("Session#runNoHangup()",
"event exit code="+b+", signal="+d+" (cmd: "+a+")");e=p(a,b,d);c(e)});setImmediate(d)}.bind(this))},forward:function(a,b,c,d){log.verbose("Session#forward()","devicePort:",a,"localPort:",b);var e=this,f=!1,g=null;"function"===typeof c?d=c:c&&(g=c);0!==b?0<e.forwardedPorts.indexOf({name:g,local:b,device:a})&&(f=!0):0<e.forwardedPorts.filter(function(b){return b.device===a&&b.name===g}).length&&(f=!0);if(f)return setImmediate(d);var k=net.createServer(function(c){log.info("Session#forward()","new client, localPort:",
b);log.verbose("Session#forward()","new client, from: "+c.remoteAddress+":"+c.remotePort);c.on("error",function(a){log.verbose("Session#forward()","inCnx::error, err:: "+a)});e.ssh.forwardOut("127.0.0.1",c.remotePort,"127.0.0.1",a,function(d,e){d?(console.log("Session#forward()","failed forwarding client localPort:",b,"(inCnx.remotePort:",c.remotePort,")=> devicePort:",a),log.warn("Session#forward()","failed forwarding client localPort:",b,"=> devicePort:",a),c.destroy()):(log.info("Session#forward()",
"connected, devicePort:",a),c.on("data",function(a){e.writable&&!0===e.writable&&!1===e.write(a)&&c.pause()}),c.on("close",function(a){log.verbose("Session#forward()","inCnx::close, had_err:",a);e.destroy()}),e.on("drain",function(){c.resume()}),e.on("data",function(a){c.write(a)}),e.on("close",function(a){log.verbose("Session#forward()","outCnx::close, had_err:",a)}))})});e.ssh.on("close",function(){k.close()});try{var h;k.listen(b,null,function(){h=k.address().port;e.forwardedPorts.push({name:g,
local:h,device:a});setImmediate(d)}.bind(this))}catch(t){setImmediate(d,t)}},getLocalPortByDevicePort:function(a){var b=null;this.forwardedPorts.forEach(function(c){c.device===a&&(b=c.local)});return b},getLocalPortByName:function(a){var b=null;this.forwardedPorts.forEach(function(c){c.name===a&&(b=c.local)});return b},runHostedAppServer:function(a,b){server.runServer(a,0,function(a,d){d&&d.port&&this.setHostedAppServerPort(d.port);b(a)}.bind(this))},setHostedAppServerPort:function(a){this.hostedAppServerPort=
a},getHostedAppServerPort:function(){return this.hostedAppServerPort}}})();
