var async=require("async"),CombinedStream=require("combined-stream"),chardet=require("chardet"),ElfParser=require("elfy").Parser,encoding=require("encoding"),fs=require("fs"),fstream=require("fstream"),log=require("npmlog"),mkdirp=require("mkdirp"),os=require("os"),path=require("path"),rimraf=require("rimraf"),shelljs=require("shelljs"),spawn=require("child_process").spawn,stripbom=require("strip-bom"),temp=require("temp"),uglify=require("terser"),util=require("util"),Validator=require("jsonschema").Validator,
zlib=require("zlib"),tarFilterPack=require("./tar-filter-pack"),commonTools=require("./common-tools"),errMsgHndl=require("./error-handler");
(function(){function v(a){this.objectId=G++;this.verbose=!1;this.silent=!0;a&&a.level&&(log.level=a.level,-1!==["warn","error"].indexOf(a.level)&&(this.silent=!1));this.noclean=!1;a&&!0===a.noclean&&(this.noclean=!0);this.nativecmd=!1;a&&!0===a.nativecmd&&(this.nativecmd=!0);this.minify=!0;a&&a.hasOwnProperty("minify")&&(this.minify=a.minify);a&&a.hasOwnProperty("deployscript")&&(this.deployscript=a.deployscript);this.excludeFiles=[];a&&a.hasOwnProperty("excludefiles")&&(a.excludefiles instanceof
Array?this.excludeFiles=a.excludefiles:this.excludeFiles.push(a.excludefiles));this.rom=!1;a&&a.hasOwnProperty("rom")&&(this.rom=a.rom);a&&a.hasOwnProperty("override-appinfo")&&(this.appInfoOverrides=JSON.parse(a["override-appinfo"]));log.verbose("Xtor Packager id="+this.objectId);this.appCount=0;this.services=[];this.pkgServiceNames=[]}function H(){this.srcDir="";this.dstDirs=[];this.valid=!1;this.dirName=this.serviceInfo=""}function I(a){log.verbose("loadAppInfo");if(0===this.appCount)return setImmediate(a);
var b=path.join(this.appDir,"appinfo.json"),b=w(b,!0);try{log.verbose("APPINFO >>"+b+"<<");this.appinfo=JSON.parse(b);if(this.appinfo.onDeviceSource)for(var c in this.appinfo.onDeviceSource){var d=this.appinfo.onDeviceSource[c],e;for(e in x)d=d.replace(e,x[e]);this.appinfo.onDeviceSource[c]=d}setImmediate(a)}catch(f){setImmediate(a,f)}}function J(a){log.verbose("overrideAppInfo");var b=this.appInfoOverrides;if(b)for(var c in b)this.appinfo[c]=b[c];setImmediate(a)}function K(a){log.verbose("checkAppInfo");
if(0===this.appCount)return setImmediate(a);log.verbose("checkAppInfo: id: "+this.appinfo.id);if(1>this.appinfo.id.length||!/^[a-z0-9.+-]*$/.test(this.appinfo.id))return log.error("Invalid app id: "+this.appinfo.id),setImmediate(a,errMsgHndl.changeErrMsg("INVALID_APPID"));if(1>this.appinfo.version.length||!/^([1-9]\d*|\d)\.([1-9]\d*|\d)\.([1-9]\d*|\d)$/.test(this.appinfo.version))return log.error("Invalid app version: "+this.appinfo.version),setImmediate(a,errMsgHndl.changeErrMsg("INVALID_APPVERSION, Check app version in appinfo.json"));
var b=path.join(__dirname,"schema/ApplicationDescription.schema");if(this.appinfo.type&&this.appinfo.type.match(/clock/gi))return setImmediate(a);async.waterfall([fs.readFile.bind(this,b,"utf-8"),function(a,b){try{var c=JSON.parse(a),d=c.required;if(d)for(key in c.properties)-1!=d.indexOf(key)&&(c.properties[key].required=!0);b(null,c)}catch(h){b(Error("Invalid JSON Schema for appinfo"))}},function(a,b){try{b(null,(new Validator).validate(this.appinfo,a))}catch(e){log.error(e),b(Error("Invalid JSON Schema"))}}.bind(this)],
function(b,d){if(b)setImmediate(a,b);else{if(d&&0<d.errors.length){var c;c="".concat("Invalid appinfo.json");for(idx in d.errors){c=c.concat("\n");var f=d.errors[idx].property+" "+d.errors[idx].message;-1<f.indexOf("instance.")&&(f=f.substring(9));c=c.concat(f)}return setImmediate(a,Error(c))}log.verbose("APPINFO is valid");setImmediate(a)}})}function L(a){log.verbose("fillAssetsField");if(0===this.appCount)return setImmediate(a);this.appinfo.assets=this.appinfo.assets||[];for(var b in this.appinfo)this.appinfo.hasOwnProperty(b)&&
p[b]&&-1===this.appinfo.assets.indexOf(this.appinfo[b])&&this.appinfo[b]&&this.appinfo.assets.push(this.appinfo[b]);var c=this.originAppDir;b=path.join(this.originAppDir,"resources");var d=[],e=[];try{if(!fs.lstatSync(b).isDirectory())return setImmediate(a,null)}catch(f){if("ENOENT"===f.code)return setImmediate(a,null)}async.series([q.bind(null,b,"appinfo.json",d,1),function(a){async.forEach(d,function(a,b){w(a,!0,function(d,f){try{var g=JSON.parse(f),h=path.dirname(a),k;for(k in g)if(g.hasOwnProperty(k)&&
p[k]&&g[k]){var l=path.join(h,g[k]),y=path.relative(c,l);-1===e.indexOf(y)&&e.push(y)}setImmediate(b,null)}catch(Ba){setImmediate(b,Error("JSON parsing error for "+a))}})},function(b){setImmediate(a,b)})},function(a){this.appinfo.assets=this.appinfo.assets.concat(e);setImmediate(a,null)}.bind(this)],function(b){setImmediate(a,b)})}function O(a){log.verbose("createTmpDir");this.tempDir=temp.path({prefix:"com.palm.ares.hermes.bdOpenwebOS"})+".d";log.verbose("temp dir = "+this.tempDir);mkdirp(this.tempDir,
a)}function P(a){log.verbose("createAppDir");if(0===this.appCount)return setImmediate(a);this.applicationDir=path.join(this.tempDir,"data/usr/palm/applications",this.appinfo.id);log.verbose("application dir = "+this.applicationDir);mkdirp(this.applicationDir,a)}function Q(a,b,c){this.cwd=process.cwd();process.chdir(a);b&&"function"==typeof b&&b(c)}function t(a,b){this.cwd&&process.chdir(this.cwd);a&&"function"==typeof a&&a(b)}function R(a){if(fs.existsSync(path.join(this.appDir,"lib/enyo")))try{var b=
require(path.join(this.appDir,"lib/enyo")),c={silly:"trace",verbose:"debug",info:"info",http:"info",warn:"warn",error:"error"};if(b.version&&"2.6.0"<=b.version){console.log("Building the application using enyo-dev tool");var d=require("enyo-dev").packager,e=this,f=path.join(e.appDir,".enyoconfig"),h=path.join(e.appDir,"dist"),l={"package":this.appDir,devMode:!this.minify,sourceMaps:!1,logLevel:c[log.level]||"warn",outFile:this.appinfo.main};Q(this.appDir);if(fs.existsSync(f))try{var g=JSON.parse(fs.readFileSync(f)),
h=path.join(e.appDir,g.outdir||"dist");l.lessPlugins=g.lessPlugins||[]}catch(k){log.warn("buildEnyo()# parsing error "+f),log.warn("buildEnyo()# err: "+k),log.warn("buildEnyo()# ignoring "+f)}fs.existsSync(h)&&shelljs.rm("-rf",h);d(l).on("end",function(){p.main=!1;shelljs.cp("-rf",path.join(e.appDir,"appinfo.json"),h);e.appDir=h;console.log("Success: the deployable application is available in:",h);e.minifyDone=!0;t(a)}).on("error",function(b){t(a,b)})}else setImmediate(a)}catch(k){t(a,k)}else setImmediate(a)}
function S(a){log.verbose("runDeployOldEnyo");if(0===this.appCount)return setImmediate(a);var b;if(!0===this.minify){var c=!1;this.deployscript&&(b=this.deployscript);if(fs.existsSync(path.join(this.appDir,"package.js"))&&this.appinfo.main&&this.appinfo.main.match(/(\.html|\.htm)$/gi)){regex=/(<script[^>]*src[ \t]*=[ \t]*['"])[^'"]*\/enyo.js(['"])/;var d=path.join(this.appDir,this.appinfo.main);if(!fs.existsSync(d))return setImmediate(a,Error(this.appinfo.main+" does not exist. please check the file path"));
fs.readFileSync(d).toString().match(regex)&&(c=!0,b||(b=path.join(this.appDir,"enyo/tools/deploy.js")))}if(!c&&b)return console.log("Ignore deploy-script because minifying is only for enyo app"),setImmediate(a);log.verbose("minifying tool:",b);if(fs.existsSync(b)){if(!fs.lstatSync(b).isFile()){setImmediate(a,"ERROR: '"+b+"' is not a valid file path");return}b=[path.resolve(b)];var e,f;this["deploy-srcroot"]||fs.existsSync(path.join(this.appDir,"deploy.json"))||fs.existsSync(path.join(this.appDir,
"index.html"))||(c=path.dirname(path.resolve(path.join(this.appDir,this.appinfo.main))),c!==path.basename(path.resolve(this.appDir))&&(console.log("Set source code root directory :",c),this["deploy-srcroot"]=c));d={};c=this["deploy-srcroot"]?path.join(this["deploy-srcroot"],"deploy.json"):path.join(this.appDir,"deploy.json");if(fs.existsSync(c)){var h=fs.readFileSync(c);try{d=JSON.parse(h),d.enyo&&!this["deploy-lib"]&&(this["deploy-lib"]=path.join(this.appDir,path.join(d.enyo,"../lib")))}catch(Aa){setImmediate(a,
"ERROR: invalid deploy.json ("+path.resolve(c)+")");return}}this["deploy-srcroot"]&&(e=path.relative(path.resolve(this.appDir),path.resolve(this["deploy-srcroot"])),b.push("-s",e),b.push("-o",path.join("deploy",path.basename(this.appDir),e)));this["deploy-enyo"]&&(f=path.relative(path.resolve(this.appDir),path.resolve(this["deploy-enyo"])),b.push("-e",f));this["deploy-lib"]&&b.push("-l","lib");var l=!1,g=f?f:d.enyo?this["deploy-srcroot"]?path.join(e,d.enyo):d.enyo:"enyo",g=path.resolve(this.appDir,
g);this.appinfo.onDeviceSource&&-1!==Object.keys(this.appinfo.onDeviceSource).indexOf("enyo")||!fs.existsSync(g)||fs.existsSync(path.join(g,"minify","package.js"))||(log.verbose("Enyo is already minified..."),l=!0,b.push("-f","enyo","-t","enyo"));if(this.appinfo.onDeviceSource)for(var k in this.appinfo.onDeviceSource)e=this.appinfo.onDeviceSource[k],k=k.replace(/[/|\\]/g,path.sep),e=e.replace(/[\\]/g,"/"),b.push("-f",k,"-t",e);this.appinfo.resolutionIndependent&&(log.verbose("Enabling resolution-independence..."),
b.push("-ri"));console.log("Minifying command...\n","node "+b.join(" ")+"\n");k=spawn("node",b,{cwd:this.appDir});e=function(a){console.log(a.toString())};k.stderr.on("data",e);k.stdout.on("data",e);k.on("exit",function(b){if(0!==b)setImmediate(a,"ERROR: minification failed");else{b=path.join(this.appDir,"deploy",path.basename(this.appDir));var c={},d;for(d in this.appinfo)this.appinfo.hasOwnProperty(d)&&!z[d]&&(c[d]=this.appinfo[d]);fs.writeFileSync(path.join(b,"appinfo.json"),JSON.stringify(c,null,
"\t"));fs.existsSync(path.join(this.appDir,"framework_config.json"))&&shelljs.cp(path.join(this.appDir,"framework_config.json"),b);l&&fs.existsSync(g)&&shelljs.cp("-rf",path.join(g,"*"),path.join(b,"build"));console.log("Packaging minified output: "+b);this.appDir=b;this.minifyDone=!0;setImmediate(a)}}.bind(this));return}this.deployscript&&setImmediate(a,"Deploy script '"+this.deployscript+"' not found.")}setImmediate(a)}function m(a,b,c){function d(a,b,c,d,e,f){n[b]&&a.push({type:b,basePath:c,relPath:d,
isSubPath:e,indRelPath:f})}function e(a,b,c,f){async.waterfall([fs.readdir.bind(null,a),function(f,g){if(0===f.length)return d(c,"dir",b,path.relative(b,a),!0,null),setImmediate(g);async.forEachSeries(f,function(f,g){var h=path.join(a,f),l=path.relative(b,h);async.waterfall([fs.lstat.bind(null,h),function(a,f){if(a.isSymbolicLink()){try{var g=fs.realpathSync(h)}catch(A){return"ENOENT"===A.code?(log.warn("The file for symbolic link ("+h+") is missing..."),setImmediate(f)):setImmediate(f,A)}var k=fs.readlinkSync(h);
if(-1!==g.indexOf(b))d(c,"symlink",b,l,!0,k);else{g=fs.statSync(h);if(g.isDirectory())return e(h,b,c,f);g.isFile()&&d(c,"file",b,l,!0,null)}}else{if(a.isDirectory())return e(h,b,c,f);a.isFile()&&d(c,"file",b,l,!0,null)}setImmediate(f)}],g)},g)}],function(a){return setImmediate(f,a)})}var f=[],h=this,l=this.minify&&!this.minifyDone?!0:!1;a=path.normalize(path.resolve(a));b=path.normalize(path.resolve(b));async.series([function(b){fs.statSync(a).isFile()?(d(f,"file",path.dirname(a),path.basename(a),
!0,null),setImmediate(b)):e(a,a,f,b)},function(a,b,c,d){try{async.forEachSeries(a,function(a,d){if(n[a.type]){if(!a.relPath)return log.verbose("copySrcToDst#_copySrcToDst#ignore 'unknown path'"),setImmediate(d);if(a.type===n.dir)return mkdirp.sync(path.join(b,a.relPath)),setImmediate(d);var e=path.dirname(path.join(b,a.relPath));fs.existsSync(e)||mkdirp.sync(e);if(a.type===n.symlink){if(a.isSubPath&&a.indRelPath){var f=path.join(b,a.relPath);fs.existsSync(f)&&fs.lstatSync(f).isSymbolicLink()&&fs.unlinkSync(f);
fs.symlinkSync(a.indRelPath,f,null)}}else if(e=path.join(a.basePath,a.relPath),fs.existsSync(e))if(c&&".js"===path.extname(e)&&-1===a.relPath.indexOf("node_modules")){log.verbose("copySrcToDst#_copySrcToDst(),require minification # src:",e);try{f=uglify.minify(fs.readFileSync(e,"utf8"));if(f.error)throw f.error;fs.writeFileSync(path.join(b,a.relPath),f.code,"utf8")}catch(T){return log.verbose(util.format("failed to uglify code %s: %s",e,T.stack)),setImmediate(d,Error(util.format("failed to minify code %s",
e)))}}else shelljs.cp("-Rf",e,path.join(b,a.relPath,".."));else log.verbose("copySrcToDst#_copySrcToDst#ignore '"+a.relPath+"'");setImmediate(d)}else log.verbose("copySrcToDst#_copySrcToDst#ignore 'unknown file type'("+a.type+")")},function(a){!a&&c&&(h.minifyDone=!0);setImmediate(d,a)})}catch(r){setImmediate(d,r)}}.bind(null,f,b,l)],function(a){c(a)})}function U(a){log.verbose("checkELFHeader");var b=this,c=new Buffer(62),d=path.resolve(path.join(this.appDir,this.appinfo.main)),e=fs.openSync(d,"r"),
f=fs.fstatSync(e),h=new ElfParser;if(62>f.size)return log.verbose("checkELFHeader():","file size is smaller than ELF Header size"),setImmediate(a);fs.read(e,c,0,62,0,function(c,f,k){if(62>f||c)return log.verbose("checkELFHeader():","err:",c,", bytesRead:",byteRead),log.verbose("checkELFHeader():","readBuf to parse ELF header is small or error occurred during reading file."),setImmediate(a);c="\u007fELF"!==k.slice(0,4).toString()?!1:!0;if(c){log.verbose("checkELFHeader():",d+" is ELF format");try{var g=
h.parseHeader(k);log.verbose("checkELFHeader():","elfHeader:",g);g.machine&&g.machine.match(/86$/)?b.architecture="i586":b.architecture=g.machine}catch(M){log.verbose("checkELFHeader():","exception:",M)}}else log.verbose("checkELFHeader():",d+" is not ELF format");fs.close(e);setImmediate(a)})}function V(a){log.verbose("copyApp()");if(0===this.appCount)return setImmediate(a);this.dataCopyCount++;log.verbose("copyApp(), copy "+this.appDir+" ==> "+this.applicationDir);m.call(this,this.appDir,this.applicationDir,
a)}function W(a){function b(a,b){log.verbose("copyAssets():","_handleAssets()");path.resolve(this.originAppDir)===path.resolve(this.appDir)?c.call(this,a,b):async.series([c.bind(this,a),d.bind(this,a)],b)}function c(a,b){log.verbose("copyAssets():","_checkAppinfo()");var c;if(path.resolve(a)==path.normalize(a))return b(Error("In appinfo.json, '"+a+"'' path must be relative to the appinfo.json."));c=path.join(this.originAppDir,a);if(0!=path.resolve(c).indexOf(this.originAppDir))return b(Error("In appinfo.json, '"+
a+"'' path must be located under app diectory."));if(!fs.existsSync(c)&&!this.rom){var d="'"+a+"'' does not exist. please check the file path.";return 0===path.basename(c).indexOf("$")?setImmediate(b):setImmediate(b,Error(d))}setImmediate(b)}function d(a,b){log.verbose("copyAssets():","_copyAssets()");log.verbose("copyAssets # '"+a+"' will be located in app directory");var c=path.join(this.originAppDir,a),d=this.appDir;async.series([function(a){fs.existsSync(d)?setImmediate(a):mkdirp(d,a)}],function(a){if(a)return setImmediate(b,
a);shelljs.cp("-Rf",c,d);setImmediate(b)})}log.verbose("copyAssets");if(0===this.appCount)return setImmediate(a);try{async.forEachSeries(this.appinfo.assets,b.bind(this),a)}catch(e){return setImmediate(a,e)}}function X(a){log.verbose("excludeIpkFileFromApp");this.excludeFiles=this.excludeFiles.concat(["[.]*[.]ipk",".DS_Store"]);setImmediate(a)}function B(a,b,c,d){async.waterfall([fs.readdir.bind(null,c),function(d,f){async.forEach(d,function(d,e){var f=path.join(c,d);async.waterfall([fs.lstat.bind(null,
f),function(c,e){var g=!1;b.test(d)&&(g=!0,a.push(f));!g&&c.isDirectory()?B(a,b,f,e):setImmediate(e)}],e)},f)}],function(a){setImmediate(d,a)})}function Y(a){log.verbose("excludeFromApp");var b=[],c=(0===this.appCount?this.excludeFiles:this.excludeFiles.concat(this.appinfo.exclude||[])).map(function(a){return a.replace(/^\./g,"^\\.").replace(/^\*/g,"").replace(/$/g,"$")},this).join("|");async.series([B.bind(this,b,new RegExp(c,"i"),this.tempDir),function(a){try{b.forEach(function(a){shelljs.rm("-rf",
a)}),setImmediate(a)}catch(e){setImmediate(a,e)}}],function(b,c){if(b)return setImmediate(a,b);setImmediate(a)})}function Z(a){log.verbose("rewriteAppInfo");if(0===this.appCount)return setImmediate(a);if(!0!==this.minify){var b={},c;for(c in this.appinfo)!this.appinfo.hasOwnProperty(c)||z[c]||aa[c]||(b[c]=this.appinfo[c]);fs.writeFileSync(path.join(this.applicationDir,"appinfo.json"),JSON.stringify(b,null,"\t"))}setImmediate(a)}function ba(a){log.verbose("rewriteAppJS");if(0===this.appCount)return setImmediate(a);
if(!0===this.minify&&this.appinfo.onDeviceSource)try{var b=path.join(this.applicationDir,"build");fs.existsSync(b)&&fs.readdirSync(b).forEach(function(a){a=path.join(b,a);if(fs.statSync(a).isFile()){for(var c=fs.readFileSync(a,"utf8"),e=/enyo.path.addPath\(.*\)|enyo.depends\(.*[\s\S]*\)/g;null!=(result=e.exec(c));)c=c.replace(result[0],result[0].replace(/[\\]/g,"/"));fs.writeFileSync(a,c,"utf8")}})}catch(c){setImmediate(a,c)}setImmediate(a)}function ca(a){log.verbose("rewriteSourcePaths");if(0===
this.appCount)return setImmediate(a);if(!0===this.minify){if(this.appinfo.onDeviceSource){var b=(this.appinfo.additionalHtmlFiles||[]).concat(this.appinfo.main),c;for(c in b){var d=b[c];try{var e=path.join(this.applicationDir,d),f=fs.readFileSync(e,"utf8"),h;for(h in this.appinfo.onDeviceSource){var l=this.appinfo.onDeviceSource[h],g=new RegExp("(<link[^>]*href[ \t]*=[ \t]*['\"][ \t]*)"+h),f=f.replace(g,"$1"+l),g=new RegExp("(<script[^>]*src[ \t]*=[ \t]*['\"][ \t]*)"+h),f=f.replace(g,"$1"+l);"enyo"==
h&&(g=/(<link[^>]*href[ \t]*=[ \t]*['"])[^'"]*build\/enyo.css(['"])/,f=f.replace(g,"$1"+l+"/enyo.css$2"),g=/(<script[^>]*src[ \t]*=[ \t]*['"])[^'"]*build\/enyo.js(['"])/,f=f.replace(g,"$1"+l+"/enyo.js$2"))}fs.writeFileSync(e,f,"utf8")}catch(k){setImmediate(a,k)}}}}else for(c in b=(this.appinfo.additionalHtmlFiles||[]).concat(this.appinfo.main),b){d=b[c];try{e=path.join(this.applicationDir,d),f=fs.readFileSync(e,"utf8"),g=/(<link[^>]*href[ \t]*=[ \t]*['"])[^'"]*build\/enyo.css(['"]).*(\/>|<\/link>)/,
f=f.replace(g,""),g=/(<script[^>]*src[ \t]*=[ \t]*['"])[^'"]*build\/enyo.js(['"]).*(\/>|<\/script>)/,f=f.replace(g,""),fs.writeFileSync(e,f,"utf8")}catch(k){setImmediate(a,k)}}setImmediate(a)}function da(a){log.verbose("createPackageDir");if(0===this.appCount)return setImmediate(a);this.rom?setImmediate(a):(this.packageDir=path.join(this.tempDir,"data/usr/palm/packages",this.appinfo.id),log.verbose("package dir = "+this.packageDir),mkdirp(this.packageDir,a))}function ea(a){log.verbose("fillPackageDir");
if(0===this.appCount)return setImmediate(a);if(this.rom)setImmediate(a);else if(this.pkgDir)shelljs.cp("-Rf",path.join(this.pkgDir,"packageinfo.json"),this.packageDir),setImmediate(a);else{var b=JSON.stringify({app:this.appinfo.id,id:this.appinfo.id,loc_name:this.appinfo.title,package_format_version:this.appinfo.uiRevision,vendor:this.appinfo.vendor,version:this.appinfo.version||"1.0.0"},null,2)+"\n";log.verbose("Generating package.json: "+b);fs.writeFile(path.join(this.packageDir,"packageinfo.json"),
b,a)}}function fa(a,b){log.verbose("loadPackageProperties");var c=this;c.packageProperties={};async.forEach(a,function(a,b){var d=path.join(a,"package.properties");fs.existsSync(d)?fs.readFile(d,function(a,d){try{log.verbose("PACKAGE PROPERTIES >>"+d+"<<");var e=d.toString().split("\n"),f,h;for(h in e)if(0==e[h].indexOf("filemode.")){f=e[h].indexOf("=");var l=e[h].substr(f+1).trim(),r=e[h].slice(9,f).trim();l.split(",").forEach(function(a){a=a.replace(/\\/g,"/").trim();var b=a.lastIndexOf("/");a=
-1!==b?a.substr(b+1):a;c.packageProperties[a]=r}.bind(this))}setImmediate(b)}catch(N){setImmediate(b,N)}}):setImmediate(b)},function(a){c.excludeFiles=c.excludeFiles.concat(["package.properties"]);setImmediate(b,a)})}function ga(a,b,c,d){this.rom?m(path.join(this.tempDir,"data"),a,d):async.series([ha.bind(this,b,c),ia.bind(this,"data"),C.bind(this,"data","data.tar.gz"),ja.bind(this),ka.bind(this),C.bind(this,"ctrl","control.tar.gz"),la.bind(this),ma.bind(this),na.bind(this,a),oa.bind(this,a)],function(a,
b){a?setImmediate(d,a):setImmediate(d)})}function ha(a,b,c){log.verbose("decidePkgName");this.pkg=0!==this.appCount?{name:a||this.appinfo.id,version:b||this.appinfo.version}:0<this.services.length?{name:a||this.services[0].serviceInfo.id||this.services[0].serviceInfo.services[0].name,version:b||"1.0.0"}:{name:a||"unknown",version:b||"1.0.0"};setImmediate(c)}function ia(a,b){function c(a,b){fs.lstat(a,function(d,e){var f=e.size;!d&&e.isDirectory()?fs.readdir(a,function(d,e){if(d)return b(d);async.forEach(e,
function(b,d){c(path.join(a,b),function(a,b){f+=b;d(a)})},function(a){b(a,f)})}):b(d,f)})}log.verbose("getFileSize");var d=this,e=path.join(this.tempDir,a);async.waterfall([c.bind(this,e)],function(a,c){!a&&c&&(log.verbose("getFileSize#Installed-Size:",c),d.size=c);setImmediate(b,a)})}function ja(a){log.verbose("createCtrlDir");this.ctrlDir=path.join(this.tempDir,"ctrl");log.verbose("ctrl dir = "+this.ctrlDir);mkdirp(this.ctrlDir,a)}function ka(a){log.verbose("createControlFile");var b=["Package: "+
this.pkg.name,"Version: "+this.pkg.version,"Section: misc","Priority: optional","Architecture: "+(this.architecture||"all"),"Installed-Size: "+(this.size||1234),"Maintainer: N/A <nobody@example.com>","Description: This is a webOS application.","webOS-Package-Format-Version: 2","webOS-Packager-Version: x.y.x",""];fs.writeFile(path.join(this.ctrlDir,"control"),b.join("\n"),a)}function la(a){log.verbose("createDebianBinary");fs.writeFile(path.join(this.tempDir,"debian-binary"),"2.0\n",a)}function C(a,
b,c){a=path.join(this.tempDir,a);log.verbose("makeTgz "+b+" from "+a);var d=this.pkgServiceNames;fstream.Reader({path:a,type:"Directory",filter:function(a){"Directory"===a.props.type&&(maskingBits=201,-1!==d.indexOf(a.props.basename)&&(maskingBits=219),a.props.mode|=a.props.mode>>>2&maskingBits);return!0}}).pipe(tarFilterPack({noProprietary:!0,fromBase:!0,permission:this.packageProperties})).pipe(zlib.createGzip()).pipe(fstream.Writer(path.join(this.tempDir,b))).on("close",c).on("error",c)}function ma(a){var b=
this.pkg.name;this.ipkFileName=b=this.pkg.version?b.concat("_"+this.pkg.version+"_"+("i586"===this.architecture?"x86":this.architecture||"all")+".ipk"):b.concat(".ipk");setImmediate(a)}function na(a,b){log.verbose("removeExistingIpk");if(0===this.appCount)return setImmediate(b);var c=path.join(a,this.ipkFileName);fs.exists(c,function(a){a?fs.unlink(c,b):setImmediate(b)})}function u(a,b){return String(a+"                                     ").slice(0,b)}function D(a,b){var c=Math.floor(Date.now()/
1E3);return u(a,16)+u(c,12)+"0     0     100644  "+u(b,10)+"`\n"}function oa(a,b){var c=this;this.ipk=path.join(a,this.ipkFileName);log.verbose("makeIpk in dir "+a+" file "+this.ipkFileName);if(this.nativecmd)shelljs.cd(this.tempDir),shelljs.exec("ar -q "+this.ipk+" debian-binary control.tar.gz data.tar.gz",{silent:this.silent}),console.log("Creating package "+filename+" in "+a),setImmediate(b);else{var d=CombinedStream.create(),e=D("debian-binary",4)+"2.0\n",f=this;d.append("!<arch>\n"+e);e=fstream.Writer(this.ipk);
["control.tar.gz","data.tar.gz"].forEach(function(a){var b=path.join(f.tempDir,a),c=fstream.Reader({path:b,type:"File"}),b=fs.statSync(b);d.append(D(a,b.size));d.append(c);0!==b.size%2&&(log.verbose("Adding a filler for file "+a),d.append("\n"))},this);d.pipe(e);e.on("close",function(){console.log("Creating package "+c.ipkFileName+" in "+a);setImmediate(b)});e.on("error",b)}}function pa(a){log.verbose("cleanupTmpDir");this.noclean?(console.log("Skipping removal of  "+this.tempDir),setImmediate(a)):
rimraf(this.tempDir,function(b){log.verbose("cleanup(): removed "+this.tempDir);setImmediate(a,b)}.bind(this))}function qa(a,b,c){log.verbose("checkDirectory: "+b);if(fs.existsSync(b))if(fs.statSync(b).isDirectory()){b=fs.realpathSync(b);if(a.force)return c();if(fs.existsSync(path.join(b,"appinfo.json")))this.appCount++,log.verbose("FOUND appinfo.json, appCount "+this.appCount),1<this.appCount?c("ERROR: only one application is supported"):(this.originAppDir=this.appDir=b,c());else if(fs.existsSync(path.join(b,
"packageinfo.json")))this.pkgDir=b,c();else if(fs.existsSync(path.join(b,"services.json")))this.svcDir=this.svcDir||[],this.svcDir=this.svcDir.concat(b),c();else if(fs.existsSync(path.join(b,"account-templates.json")))c("ERROR: account directory support is not yet implemented");else{var d=[];this.svcDir=this.svcDir||[];this.svcDir=this.svcDir.concat(b);E.call(this,d,function(a){0<d.length?c():c("ERROR: '"+b+"' has no meta files such as appinfo.json")})}}else c("ERROR: '"+b+"' is not a directory");
else c("ERROR: directory '"+b+"' does not exist")}function E(a,b){var c=[].concat(this.svcDir||this.originAppDir||[]),d=[];if(0===c.length)return setImmediate(b);async.forEach(c,function(b,c){q(b,"services.json",d,3,function(b){if(b)return setImmediate(c,b);d.forEach(function(b){var c=new H;c.srcDir=path.dirname(b);c.dirName=path.basename(c.srcDir);a.push(c)});setImmediate(c,b)})},function(a){setImmediate(b,a)})}function q(a,b,c,d,e){if(0>=d)return e();async.waterfall([fs.readdir.bind(null,a),function(e,
h){async.forEach(e,function(e,f){var h=path.join(a,e);async.waterfall([fs.lstat.bind(null,h),function(a,f){a.isFile()?(e===b&&c.push(h),f()):a.isDirectory()?q(h,b,c,d-1,f):f()}],f)},h)}],function(a){e(a)})}function ra(a){log.verbose("loadServiceInfo");for(idx in this.services){var b=path.join(this.services[idx].srcDir,"services.json");try{var c=fs.readFileSync(b),d=JSON.parse(c);d.hasOwnProperty("id")&&d.hasOwnProperty("services")&&(this.services[idx].serviceInfo=d,this.services[idx].valid=!0)}catch(e){return setImmediate(a,
e)}}log.verbose("num of serviceInfo: "+this.services.length);setImmediate(a)}function sa(a){log.verbose("checkServiceInfo");if(0===this.appCount)return setImmediate(a);var b=this.appinfo.id;this.services.forEach(function(c){!1!==c.valid&&[c.serviceInfo.id].forEach(function(c){if(-1===c.indexOf(b+"."))return setImmediate(a,Error('service name "'+c+'" must be subdomain of app id "'+b+'"'))}.bind(this))}.bind(this));setImmediate(a)}function ta(a){log.verbose("createServiceDir");this.services.forEach(function(b){!1!==
b.valid&&[b.serviceInfo.id].forEach(function(c){c=path.join(this.tempDir,"data/usr/palm/services",c);b.dstDirs.push(c);try{mkdirp.sync(c)}catch(d){return setImmediate(a,d)}}.bind(this))}.bind(this));setImmediate(a)}function ua(a){log.verbose("copyService");var b=this,c=this.services.filter(function(a){return a.valid});try{async.forEachSeries(c,function(a,c){async.forEach(a.dstDirs,function(c,d){b.dataCopyCount++;m.call(b,a.srcDir,c,d)},c)},a)}catch(d){setImmediate(a,d)}}function va(a){log.verbose("addServiceInPkgInfo");
if(0===this.appCount)return setImmediate(a);if(this.rom)setImmediate(a);else{var b=path.join(this.packageDir,"packageinfo.json"),c;try{var d=fs.readFileSync(b),e=0;log.verbose("PACKAGEINFO >>"+d+"<<");c=JSON.parse(d)}catch(f){console.error(f),setImmediate(a,f)}this.services.filter(function(a){return a.valid}).forEach(function(a){[a.serviceInfo.id].forEach(function(a){this.pkgServiceNames.push(a);e++}.bind(this))}.bind(this));0<e?(c.services=this.pkgServiceNames,d=JSON.stringify(c,null,2)+"\n",log.verbose("Modified package.json: "+
d),fs.writeFile(path.join(this.packageDir,"packageinfo.json"),d,a)):setImmediate(a)}}function wa(a){log.verbose("removeServiceFromAppDir");if(0===this.appCount)return setImmediate(a);var b=this.applicationDir,c=!1,d=fs.readdirSync(b);-1!==d.indexOf("services")&&(b=path.join(this.applicationDir,"services"),fs.statSync(b).isDirectory()&&(c=!0));if(!0===c)try{shelljs.rm("-rf",b)}catch(h){console.log("ERROR:"+h)}else for(var e in this.services){var f=this.services[e].dirName;d.forEach(function(a){if(f===
a)try{var b=path.join(this.applicationDir,this.services[e].dirName);shelljs.rm("-rf",b)}catch(g){console.log("ERROR:"+g)}},this)}setImmediate(a)}function xa(a,b,c){log.verbose("copyData ** Only run when force packaging");if(b&&0===this.dataCopyCount){var d=path.join(this.tempDir,"data");async.forEachSeries(a,function(a,b){m(a,d,b)},function(a,b){setImmediate(c,a)}.bind(this))}else return setImmediate(c)}function ya(a,b){this.oldmask=process.umask(a);setImmediate(b)}function za(a){this.oldmask&&process.umask(this.oldmask);
setImmediate(a)}function w(a,b,c){var d=fs.readFileSync(a),e=chardet.detect(new Buffer(d));-1===["UTF-8","ISO-8895-1"].indexOf(e)&&(log.verbose("Current Encoding Type>> "+e+"<<"),d=encoding.convert(d,"UTF-8",e));d=stripbom(d);b&&fs.writeFileSync(a,d,{encoding:"utf8"});"undefined"!==c&&"function"===typeof c&&setImmediate(c,null,d);return d}log.heading="packager";log.level="warn";var x={$frameworks:"/usr/palm/frameworks","$enyo-framework":"/usr/palm/frameworks/enyo"},z={onDeviceSource:!0,additionalHtmlFiles:!0,
assets:!0,exclude:!0},aa={containerJS:!0,containerCSS:!0},p={main:!0,icon:!0,largeIcon:!0,bgImage:!0,splashBackground:!0,imageForRecents:!0,sysAssetsBasePath:!0},n={file:"file",dir:"dir",symlink:"symlink"},F={};"undefined"!==typeof module&&module.exports&&(module.exports=F);var G=0;F.Packager=v;v.prototype={checkInputDirectories:function(a,b,c){log.verbose("checkInputDirectories: "+a);var d=this;async.forEachSeries(a,qa.bind(this,b),function(a,f){a?setImmediate(c,a):b.force||0!==this.appCount?commonTools.appdata.compareProfile("signage",
function(a,b){if(b&&d.appDir&&fs.existsSync(path.join(d.appDir,"content")))return setImmediate(c,"ERROR: APP_DIR should not contain 'content' folder or file");setImmediate(c)}):setImmediate(c,"ERROR: At least an APP_DIR must be specified")}.bind(this))},generatePackage:function(a,b,c,d){log.verbose("generatePackage: from "+a);this.dataCopyCount=0;this.minifyDone=this.minify?!1:!0;async.series([this.checkInputDirectories.bind(this,a,c),ya.bind(this,0),I.bind(this),J.bind(this),K.bind(this),O.bind(this),
P.bind(this),S.bind(this),R.bind(this),U.bind(this),L.bind(this),W.bind(this),V.bind(this),X.bind(this),Z.bind(this),ba.bind(this),ca.bind(this),da.bind(this),ea.bind(this),E.bind(this,this.services),ra.bind(this),sa.bind(this),ta.bind(this),ua.bind(this),va.bind(this),wa.bind(this),xa.bind(this,a,c.force),fa.bind(this,a),Y.bind(this),ga.bind(this,b,c.pkgname,c.pkgversion),za.bind(this),pa.bind(this)],function(a,b){a?setImmediate(d,a):setImmediate(d,null,{ipk:this.ipk,msg:"Success"})}.bind(this))}}})();
