var fs=require("fs"),async=require("async"),npmlog=require("npmlog"),util=require("util"),luna=require("./luna"),path=require("path"),streamBuffers=require("stream-buffers"),os=require("os"),mkdirp=require("mkdirp"),fstream=require("fstream"),spawn=require("child_process").spawn,novacom=require("./novacom"),commonTools=require("./common-tools"),novacomUsb=require("./novacom-usb");
(function(){var q=npmlog;q.heading="pull";q.level="warn";var D={pull:function(k,l){function x(a,c){q.verbose("Pull","err: ",a,"result:",c);if(!a){y=(new Date).getTime();var d=(y-z)/1E3;console.log(n+" file(s) pulled");console.log(Math.round(m/(1024*d))+" KB/s ("+m+" bytes in "+d+"s)")}return setImmediate(l,a,c)}if("function"!==typeof l)throw Error("Missing completion callback (next="+util.inspect(l)+")");var p,n=0,m=0,z=(new Date).getTime(),y=(new Date).getTime(),b=k.sourcePath,a=k.destinationPath,
t=!1,r=novacomUsb.getNovacomPath(),A=new streamBuffers.WritableStreamBuffer,B=new streamBuffers.WritableStreamBuffer,C=new streamBuffers.WritableStreamBuffer,u=new streamBuffers.WritableStreamBuffer,v=[];commonTools.appdata.compareProfile("watch",function(a,c){t=c});String.prototype.replaceAll=function(a,c,b){var d=this+"",e=-1;if("string"===typeof a)if(b)for(a.toLowerCase();-1!==(e=d.toLowerCase().indexOf(a,0<=e?e+c.length:0));)d=d.substring(0,e)+c+d.substring(e+a.length);else return this.split(a).join(c);
return d};async.waterfall([function(a){var c=new novacom.Resolver;async.waterfall([c.load.bind(c)],function(){var d=c.devices,b;for(b in d)if(d[b].name==k.device){p=d[b].id;break}setImmediate(a)})},function(a){new novacom.Session(k.device,a)},function(d,c){q.info("pull#transferFiles():","sourcePath "+b,"destinationPath "+a);try{var l=b,w=b.length;b=b.replaceAll(" ","\\ ");var e="[ -f "+b+" ] && echo 'f' || echo 'nf'";d.run(e,null,A,null,function(){console.log("Copying data ....");z=(new Date).getTime();
if("f\n"==A.getContentsAsString()){var f;fs.exists(a,function(e){e&&(stats=fs.lstatSync(a),stats.isDirectory()&&(a=a+path.sep+path.basename(l)));if(t){f=p?spawn(r,["get","file://"+b,"-d",p]):spawn(r,["get","file://"+b]);n++;var g=fs.createWriteStream(a,{encoding:"binary"});f.stdout.on("data",function(a){g.write(a)});f.stdin.end();f.stderr.on("data",function(a){setImmediate(c,a)});f.on("exit",function(d){g.end();a=a.replaceAll("\\\\","\\");a=a.replaceAll("//","/");k.ignore||console.log("Pull: "+b+
" -> "+a);stat=fs.lstatSync(a);m+=stat.size;setImmediate(c)})}else d.get(b,a,function(d){if(d)return setImmediate(c,d);k.ignore||console.log("Pull: "+b+" -> "+a);stat=fs.lstatSync(a);n++;m+=stat.size;setImmediate(c)})})}else e="[ -d "+b+" ] && echo 'd' || echo 'nd'",d.run(e,null,B,null,function(){if("d\n"==B.getContentsAsString()){a=path.resolve(path.join(a,path.basename(b)));try{var f=fs.lstatSync(a);if(!f.isDirectory())return c(Error(a+" exists but not a directory."))}catch(g){if(g&&"ENOENT"===
g.code)mkdirp.sync(a);else return c(g)}k.ignore||console.log("Pull: "+b+" -> "+a);async.waterfall([function(c){e="find "+b+" -type d -follow -print";d.run(e,null,C,null,function(){var d=C.getContentsAsString().split("\n");async.eachSeries(d,function(d,c){var b=path.join(a,d.substring(w));mkdirp(b,function(f){k.ignore||path.resolve(b)===a||console.log("Pull: "+d+" -> "+b);setImmediate(c,f)})},function(a){setImmediate(c,a)})})},function(c){e="find "+b+" -type f -follow -print";d.run(e,null,u,null,function(){if(0==
u.size())return setImmediate(c);v=u.getContentsAsString().split("\n");v.pop();async.eachSeries(v,function(b,e){if(t){var g;g=p?spawn(r,["get","file://"+b.replaceAll(" ","\\ "),"-d",p]):spawn(r,["get","file://"+b.replaceAll(" ","\\ ")]);n++;var h=path.join(a,b.substring(w)),l=fs.createWriteStream(h,{encoding:"binary"});g.stdout.on("data",function(a){l.write(a)});g.stdin.end();g.stderr.on("data",function(a){setImmediate(c,a)});g.on("exit",function(a){l.end();h=h.replaceAll("\\\\","\\");h=h.replaceAll("//",
"/");k.ignore||console.log("Pull: "+b+" -> "+h);f=fs.lstatSync(h);m+=f.size;setImmediate(e)})}else{var h=path.join(a,b.substring(w));d.get(b.replaceAll(" ","\\ "),h,function(a){if(a)return setImmediate(c,a);k.ignore||console.log("Pull: "+b+" -> "+h);n++;f=fs.lstatSync(h);m+=f.size;setImmediate(e)})}},function(a){setImmediate(c,a)})})}],function(a,b){setImmediate(c,a,b)})}else return setImmediate(c,Error("Source does not exist."))})})}catch(f){1==f.code&&(f=Error("Wrong path: "+f)),x(f)}}],function(a,
b){x(a,b)})}};"undefined"!==typeof module&&module.exports&&(module.exports=D)})();
