var fs=require("fs"),async=require("async"),npmlog=require("npmlog"),util=require("util"),path=require("path"),streamBuffers=require("stream-buffers"),ssh2=require("ssh2"),novacom=require("./novacom"),spawn=require("child_process").spawn,commonTools=require("./common-tools"),novacomUsb=require("./novacom-usb");os=require("os");
(function(){var n=npmlog;n.heading="push";n.level="warn";var H={push:function(p,h){function B(b){for(var a=0;a<b.length;a++)-1<os.platform().indexOf("win")&&(b=b.replace("\\","/"));return b}function C(b){t.run("/bin/mkdir -p "+b,null,null,null,function(a){a&&(1==a.code&&(a=Error("Failed creation of directory due to permission error in the destination path")),u(a))})}function u(b,a){n.verbose("Push","err: ",b,"result:",a);if(!b){D=(new Date).getTime();var c=(D-E)/1E3;console.log(x+" file(s) pushed");
console.log(Math.round(v/(1024*c))+" KB/s ("+v+" bytes in "+c+"s)")}setImmediate(h,b,a)}if("function"!==typeof h)throw Error("Missing completion callback (next="+util.inspect(h)+")");path.basename(process.argv[1]).replace(/.js/,"");var l,x=0,v=0,E=(new Date).getTime(),D=(new Date).getTime(),k=p.sourcePath,w=p.destinationPath,y=!1,F=new streamBuffers.WritableStreamBuffer,q=novacomUsb.getNovacomPath(),t;commonTools.appdata.compareProfile("watch",function(b,a){y=a});String.prototype.replaceAll=function(b,
a,c){var f=this+"",e=-1;if("string"===typeof b)if(c)for(b.toLowerCase();-1!==(e=f.toLowerCase().indexOf(b,0<=e?e+a.length:0));)f=f.substring(0,e)+a+f.substring(e+b.length);else return this.split(b).join(a);return f};async.waterfall([function(b){var a=new novacom.Resolver;async.waterfall([a.load.bind(a)],function(){var c=a.devices,f;for(f in c)if(c[f].name==p.device){l=c[f].id;break}setImmediate(b)})},function(b){t=new novacom.Session(p.device,b)},function(b){n.info("push#transferFiles():","sourcePath "+
k,"destinationPath "+w);try{if(stats=fs.statSync(k),console.log("Copying data ...."),E=(new Date).getTime(),stats.isDirectory()){var a=function(b,d,c){var m=fs.readdirSync(b),e=-1;if(0==m.length)return setImmediate(c);async.eachSeries(m,function(G,A){e++;var r=path.join(b,G),h=path.join(k,r.substring(f));stat=fs.statSync(r);if(stat.isDirectory())stat.isDirectory()&&async.waterfall([function(b){var a=path.join(w,r.substring(f)),a=B(a),a=a.replaceAll(" ","\\ ");y?(a=l?spawn(q,["run","file:///bin/mkdir "+
a,"-d",l]):spawn(q,["run","file:///bin/mkdir "+a]),a.stdin.end(),a.stderr.on("data",function(a){setImmediate(b,a)}),a.on("close",function(a){setImmediate(b,null,r,!0)})):(C(a),setImmediate(b,null,r,!0))},a],function(a,b){a?u(a,b):setImmediate(A)});else{var g=path.join(w,r.substring(f)),g=B(g),g=g.replaceAll(" ","\\ "),z;if(y){z=l?spawn(q,["put","file://"+g,"-d",l]):spawn(q,["put","file://"+g]);v+=stat.size;x++;var n=fs.createReadStream(r);n.on("error",function(a){setImmediate(c,a)});n.on("data",function(a){z.stdin.write(a)});
n.on("end",function(){z.stdin.end()});z.stderr.on("data",function(a){setImmediate(c,a)});z.on("close",function(a){g=g.replaceAll("//","/");p.ignore||console.log("Push: "+h+" -> "+g);1==d?e>=m.length-1?setImmediate(c):setImmediate(A):setImmediate(A)})}else t.put(h,g,function(a){if(a)return 1==a.code&&(a=Error("File creation in device failed due to permission error in destination path")),setImmediate(c,a);v+=stat.size;x++;p.ignore||console.log("Push: "+h+" -> "+g);1==d?e>=m.length-1?setImmediate(c):
setImmediate(A):setImmediate(A)})}},function(a){setImmediate(c,a)})},c=path.resolve(k),f=c.length,e=w,e=B(e),e=e.replaceAll(" ","\\ ");async.waterfall([function(a){t.run("[ -d "+w+" ] && echo 'd' || echo 'nd'",null,F,null,function(){if("d\n"==F.getContentsAsString())setImmediate(a,null,c,!1);else{var b;y?(b=l?spawn(q,["run","file:///bin/mkdir "+e,"-d",l]):spawn(q,["run","file:///bin/mkdir "+e]),b.stdin.end(),b.stderr.on("data",function(b){setImmediate(a,b)}),b.on("close",function(b){setImmediate(a,
null,c,!1)})):(C(e),setImmediate(a,null,c,!1))}})},a],u)}else if(stats.isFile()){var h=new streamBuffers.WritableStreamBuffer,c=k,d=w,d=B(d),d=d.replaceAll(" ","\\ ");async.waterfall([function(a){t.run("[ -d "+d+" ] && echo 'd' || echo 'nd'",null,h,null,function(){var b;"d\n"==h.getContentsAsString()&&(d=d+"/"+path.basename(k),d=d.replaceAll(" ","\\ "));if(y){b=l?spawn(q,["put","file://"+d,"-d",l]):spawn(q,["put","file://"+d]);v+=stats.size;x++;var c=fs.createReadStream(k);c.on("error",function(b){setImmediate(a,
b)});c.on("data",function(a){b.stdin.write(a)});c.on("end",function(){b.stdin.end()});b.stderr.on("data",function(b){setImmediate(a,b)});b.on("close",function(b){d=d.replaceAll("//","/");p.ignore||console.log("Push: "+path.basename(k)+" -> "+d);setImmediate(a)})}else t.put(k,d,function(b){if(b)return 1==b.code&&(b=Error("File creation in device failed due to permission error in destination path")),setImmediate(a,b);v+=stats.size;x++;d=d.replaceAll("//","/");p.ignore||console.log("Push: "+path.basename(k)+
" -> "+d);setImmediate(a)})})}],function(a,b){u(a,b)})}}catch(m){1==m.code&&(m=Error("Wrong path: "+m)),u(m)}}],u)}};"undefined"!==typeof module&&module.exports&&(module.exports=H)})();
