var async=require("async"),path=require("path"),npmlog=require("npmlog"),fs=require("fs"),childprocess=require("child_process"),commonTools=require("./common-tools"),novacom=require("./novacom"),novacomusb=require("./novacom-usb");
(function(){var e=npmlog;e.heading="logger";e.level="warn";var d={log:e,novacom_path:null,deviceId:null,enableRoot:function(c,a){console.log("Enable Root ....");d.options=c;d.novacom_path=novacomusb.getNovacomPath();async.waterfall([this._getdeviceInfo,function(b){function a(b){d._copyFile(path.join(g,"novacom-usb-auth-root.json"),h,function(a){if(a)return setImmediate(b,a);fs.chmod(e,384,b)})}var c=process.env.HOME||process.env.USERPROFILE,k=commonTools.appdata.getPath();!c&&process.env.HOMEPATH&&
process.env.HOMEDRIVE&&(c=path.join(process.env.HOMEDRIVE,process.env.HOMEPATH));var g=path.join(__dirname,"setting-files"),e=path.join(c,".ssh","webos_w2-linux-root"),l=path.join(c,".ssh","webos_w2-linux-root.ppk"),h=path.join(k,"novacom-usb-auth.json");d._copyFile(path.join(g,"keys","webos_w2-linux-root"),e,function(f){if(f)return setImmediate(b,f);-1<process.platform.indexOf("win")?d._copyFile(path.join(g,"keys","webos_w2-linux-root.ppk"),l,function(d){if(d)return setImmediate(b,d);a(b)}):a(b)})},
function(b){b(null,"checksum_root")},this._checkPrefFile,this._removeOldPref,this._putPref,function(b){var a=childprocess.spawn;novacomusb.getNovacomPath();a=d.deviceId?a(d.novacom_path,["run","file:///usr/bin/killall novacomd","-d",d.deviceId]):a(d.novacom_path,["run","file:///usr/bin/killall novacomd"]);a.on("error",function(a){e.silly("_killNovacomd error :: ",a)});a.stdin.end();a.on("close",function(a){setTimeout(b,4E3)})},this._reboot],a)},disableRoot:function(c,a){console.log("Disable Root ....");
d.options=c;d.novacom_path=novacomusb.getNovacomPath();async.waterfall([this._getdeviceInfo,function(a){function b(a){d._copyFile(path.join(e,"novacom-usb-auth-dev.json"),h,function(b){if(b)return setImmediate(a,b);fs.chmod(m,384,a)})}var c=process.env.HOME||process.env.USERPROFILE,k=process.env.APPDATA||process.env.HOME||process.env.USERPROFILE;!c&&process.env.HOMEPATH&&process.env.HOMEDRIVE&&(c=path.join(process.env.HOMEDRIVE,process.env.HOMEPATH));var e=path.join(__dirname,"setting-files"),m=path.join(c,
".ssh","webos_w2-linux-dev"),l=path.join(c,".ssh","webos_w2-linux-dev.ppk"),h=path.join(k,"novacom-usb-auth.json");d._copyFile(path.join(e,"keys","webos_w2-linux-dev"),m,function(c){if(c)return setImmediate(a,c);-1<process.platform.indexOf("win")?d._copyFile(path.join(e,"keys","webos_w2-linux-dev.ppk"),l,function(c){if(c)return setImmediate(a,c);b(a)}):b(a)})},function(a){a(null,"checksum_dev")},this._checkPrefFile,this._removeOldPref,this._putPref,this._reboot],a)},_checkPrefFile:function(c,a){fs.exists(path.join(__dirname,
"setting-files",c),function(b){b?a(null,c):setImmediate(a,"checksum file is not found")})},_removeOldPref:function(c,a){var b=childprocess.spawn,b=d.deviceId?b(d.novacom_path,["run","file:///bin/rm /var/luna/preferences/developer_key","-d",d.deviceId]):b(d.novacom_path,["run","file:///bin/rm /var/luna/preferences/developer_key"]);b.stderr.on("data",function(a){e.silly("_removeOldPref error :: ",a)});b.stdin.end();b.on("close",function(b){a(null,c)})},_putPref:function(c,a){var b=childprocess.spawn,
f;f=d.deviceId?b(d.novacom_path,["put","file:///var/luna/preferences/developer_key","-d",d.deviceId]):b(d.novacom_path,["put","file:///var/luna/preferences/developer_key"]);fs.readFile(path.join(__dirname,"setting-files",c),function(a,b){f.stdin.write(b);f.stdin.end()});f.stderr.on("data",function(b){setImmediate(a,b)});f.on("close",function(b){a(null)})},_reboot:function(c){console.log("Device will reboot");var a=childprocess.spawn,a=d.deviceId?a(d.novacom_path,["run","file:///sbin/reboot -f","-d",
d.deviceId]):a(d.novacom_path,["run","file:///sbin/reboot -f"]);a.stdin.end();a.on("error",function(a){e.silly("_reboot error :: ",a)});a.on("close",function(a){c(null)})},_copyFile:function(c,a,b){function d(a){e||(b(a),e=!0)}var e=!1;c=fs.createReadStream(c);c.on("error",function(a){d(a)});a=fs.createWriteStream(a);a.on("error",function(a){d(a)});a.on("close",function(a){d()});c.pipe(a)},_getdeviceInfo:function(c){var a=new novacom.Resolver;async.series([a.load.bind(a),function(b){for(var c in a.devices)if(a.devices[c].name==
d.options.device){d.deviceId=a.devices[c].id;break}b()}],function(){c()})}};"undefined"!==typeof module&&module.exports&&(module.exports=d)})();
